# 命名example：g_robotLength
global g_homeStatus
global upper_G_length
global upper_G_angle
global lower_G_length
global lower_G_angle
global last_BLDC_Down_Motion
global last_FLDC_Down_Motion
global last_BLDC_Up_Motion
global last_FLDC_Up_Motion
global jogStrickEnable