# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgHintBox.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgHintBox(object):
    def setupUi(self, DlgHintBox):
        DlgHintBox.setObjectName("DlgHintBox")
        DlgHintBox.resize(645, 489)
        self.gridLayout = QtWidgets.QGridLayout(DlgHintBox)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgTL = QtWidgets.QWidget(DlgHintBox)
        self.wdgTL.setMinimumSize(QtCore.QSize(129, 134))
        self.wdgTL.setStyleSheet("background-image:url(image/msg_green/msg_tl.png)")
        self.wdgTL.setObjectName("wdgTL")
        self.gridLayout.addWidget(self.wdgTL, 0, 0, 1, 1)
        self.wdgT = QtWidgets.QWidget(DlgHintBox)
        self.wdgT.setMinimumSize(QtCore.QSize(0, 134))
        self.wdgT.setStyleSheet("background-image:url(image/msg_green/msg_t.png)")
        self.wdgT.setObjectName("wdgT")
        self.gridLayout.addWidget(self.wdgT, 0, 1, 1, 1)
        self.wdgTR = QtWidgets.QWidget(DlgHintBox)
        self.wdgTR.setMinimumSize(QtCore.QSize(56, 134))
        self.wdgTR.setStyleSheet("background-image:url(image/msg_green/msg_tr.png)")
        self.wdgTR.setObjectName("wdgTR")
        self.gridLayout.addWidget(self.wdgTR, 0, 2, 1, 1)
        self.wdgMain = QtWidgets.QWidget(DlgHintBox)
        self.wdgMain.setMinimumSize(QtCore.QSize(0, 0))
        self.wdgMain.setStyleSheet("#wdgMain{\n"
"    background-image:url(image/msg_green/msg_center.png);\n"
"}\n"
"\n"
"QWidget{\n"
"    font:24px \"Arial\";\n"
"    color:rgb(240, 240, 200);\n"
"}\n"
"\n"
"QPushButton#btnConfirm{\n"
"    font: 24px \"Arial\";\n"
"    background-color:#ff00ff;\n"
"    color:rgb(241, 231, 255);\n"
"}\n"
"\n"
"#chbKnown{\n"
"    font:12px \"Arial\";\n"
"    color:rgb(240, 240, 0);\n"
"}\n"
"")
        self.wdgMain.setObjectName("wdgMain")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wdgMain)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblHintText = QtWidgets.QLabel(self.wdgMain)
        self.lblHintText.setStyleSheet("font: 36px \"Arial\";\n"
"color:#ffff90;")
        self.lblHintText.setText("")
        self.lblHintText.setObjectName("lblHintText")
        self.gridLayout_2.addWidget(self.lblHintText, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.btnConfirm = QtWidgets.QPushButton(self.wdgMain)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfirm.sizePolicy().hasHeightForWidth())
        self.btnConfirm.setSizePolicy(sizePolicy)
        self.btnConfirm.setMinimumSize(QtCore.QSize(100, 40))
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout.addWidget(self.btnConfirm)
        self.chbKnown = QtWidgets.QCheckBox(self.wdgMain)
        self.chbKnown.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.chbKnown.setObjectName("chbKnown")
        self.horizontalLayout.addWidget(self.chbKnown)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.horizontalLayout.setStretch(0, 7)
        self.horizontalLayout.setStretch(3, 3)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)
        self.gridLayout.addWidget(self.wdgMain, 1, 0, 1, 3)
        self.wdgBL = QtWidgets.QWidget(DlgHintBox)
        self.wdgBL.setMinimumSize(QtCore.QSize(0, 41))
        self.wdgBL.setStyleSheet("background-image:url(image/msg_green/msg_bl.png)")
        self.wdgBL.setObjectName("wdgBL")
        self.gridLayout.addWidget(self.wdgBL, 2, 0, 1, 1)
        self.wdgB = QtWidgets.QWidget(DlgHintBox)
        self.wdgB.setMinimumSize(QtCore.QSize(0, 41))
        self.wdgB.setStyleSheet("background-image:url(image/msg_green/msg_b.png)")
        self.wdgB.setObjectName("wdgB")
        self.gridLayout.addWidget(self.wdgB, 2, 1, 1, 1)
        self.wdgBR = QtWidgets.QWidget(DlgHintBox)
        self.wdgBR.setMinimumSize(QtCore.QSize(0, 41))
        self.wdgBR.setStyleSheet("background-image:url(image/msg_green/msg_br.png)")
        self.wdgBR.setObjectName("wdgBR")
        self.gridLayout.addWidget(self.wdgBR, 2, 2, 1, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout.setRowStretch(1, 1)

        self.retranslateUi(DlgHintBox)
        QtCore.QMetaObject.connectSlotsByName(DlgHintBox)

    def retranslateUi(self, DlgHintBox):
        _translate = QtCore.QCoreApplication.translate
        DlgHintBox.setWindowTitle(_translate("DlgHintBox", "Dialog"))
        self.btnConfirm.setText(_translate("DlgHintBox", "OK"))
        self.chbKnown.setText(_translate("DlgHintBox", "don\'t show this again"))
