# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgJoystick.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgJoysitck(object):
    def setupUi(self, DlgJoysitck):
        DlgJoysitck.setObjectName("DlgJoysitck")
        DlgJoysitck.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgJoysitck.resize(964, 843)
        DlgJoysitck.setStyleSheet("QDialog{background-color:#000}")
        self.gridLayout = QtWidgets.QGridLayout(DlgJoysitck)
        self.gridLayout.setContentsMargins(5, 5, 5, 5)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgMain = QtWidgets.QWidget(DlgJoysitck)
        self.wdgMain.setStyleSheet("#wdgMain{background-color:#4D84AD}")
        self.wdgMain.setObjectName("wdgMain")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.wdgMain)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnStop = QtWidgets.QPushButton(self.wdgMain)
        self.btnStop.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnStop.sizePolicy().hasHeightForWidth())
        self.btnStop.setSizePolicy(sizePolicy)
        self.btnStop.setMinimumSize(QtCore.QSize(324, 150))
        self.btnStop.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color:#bbb;\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(155, 155, 155, 255), stop:0.2 rgba(255, 255, 255, 255), stop:0.5 rgba(255, 255, 255, 255), stop:0.75 rgba(200, 200, 200, 255),  stop:1 rgba(155, 155, 155, 255));\n"
"}")
        self.btnStop.setObjectName("btnStop")
        self.horizontalLayout.addWidget(self.btnStop)
        self.gridLayout_2.addLayout(self.horizontalLayout, 1, 0, 1, 1)
        self.wdgRobot = AnimationJoystickWidget(self.wdgMain)
        self.wdgRobot.setMinimumSize(QtCore.QSize(690, 628))
        self.wdgRobot.setMaximumSize(QtCore.QSize(690, 628))
        self.wdgRobot.setStyleSheet("image:url(image/robot.png)")
        self.wdgRobot.setObjectName("wdgRobot")
        self.wdgForward = QtWidgets.QWidget(self.wdgRobot)
        self.wdgForward.setGeometry(QtCore.QRect(340, 160, 200, 200))
        self.wdgForward.setMinimumSize(QtCore.QSize(200, 200))
        self.wdgForward.setMaximumSize(QtCore.QSize(200, 200))
        self.wdgForward.setStyleSheet("image:url(image/joystick_forward.png)")
        self.wdgForward.setObjectName("wdgForward")
        self.wdgRight = QtWidgets.QWidget(self.wdgRobot)
        self.wdgRight.setGeometry(QtCore.QRect(210, 200, 128, 128))
        self.wdgRight.setMinimumSize(QtCore.QSize(128, 128))
        self.wdgRight.setMaximumSize(QtCore.QSize(128, 128))
        self.wdgRight.setStyleSheet("image:url(image/joystick_right.png)")
        self.wdgRight.setObjectName("wdgRight")
        self.wdgBackward = QtWidgets.QWidget(self.wdgRobot)
        self.wdgBackward.setGeometry(QtCore.QRect(210, 90, 128, 128))
        self.wdgBackward.setMinimumSize(QtCore.QSize(128, 128))
        self.wdgBackward.setMaximumSize(QtCore.QSize(128, 128))
        self.wdgBackward.setStyleSheet("image:url(image/joystick_backward.png)")
        self.wdgBackward.setObjectName("wdgBackward")
        self.wdgLeft = QtWidgets.QWidget(self.wdgRobot)
        self.wdgLeft.setGeometry(QtCore.QRect(380, 80, 128, 128))
        self.wdgLeft.setMinimumSize(QtCore.QSize(128, 128))
        self.wdgLeft.setMaximumSize(QtCore.QSize(128, 128))
        self.wdgLeft.setStyleSheet("image:url(image/joystick_left.png)")
        self.wdgLeft.setObjectName("wdgLeft")
        self.gridLayout_2.addWidget(self.wdgRobot, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.wdgMain, 0, 0, 1, 1)

        self.retranslateUi(DlgJoysitck)
        QtCore.QMetaObject.connectSlotsByName(DlgJoysitck)

    def retranslateUi(self, DlgJoysitck):
        _translate = QtCore.QCoreApplication.translate
        DlgJoysitck.setWindowTitle(_translate("DlgJoysitck", "Dialog"))
        self.btnStop.setText(_translate("DlgJoysitck", "CLOSE"))
from FunctionLib_UI.WidgetButton import AnimationJoystickWidget
