# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FunctionLib_UI/ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from FunctionLib_UI.WidgetButton import *

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1920, 1020)
        MainWindow.setMinimumSize(QtCore.QSize(1920, 1020))
        MainWindow.setStyleSheet("#MainWindow{background-color: rgb(0, 0, 0);}\n"
"\n"
"#centralwidget{background-color: rgb(0, 0, 0);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("#centralwidget{\n"
"    background-color: rgb(55, 96, 125);\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.stkMain = QtWidgets.QStackedWidget(self.centralwidget)
        self.stkMain.setStyleSheet("#stkMain > QWidget{\n"
"    background-color:#4D84AD;\n"
"}")
        self.stkMain.setObjectName("stkMain")
        self.pgHome = QtWidgets.QWidget()
        self.pgHome.setObjectName("pgHome")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.pgHome)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.wdgModeSelection = QtWidgets.QWidget(self.pgHome)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgModeSelection.sizePolicy().hasHeightForWidth())
        self.wdgModeSelection.setSizePolicy(sizePolicy)
        self.wdgModeSelection.setMinimumSize(QtCore.QSize(1024, 576))
        self.wdgModeSelection.setMaximumSize(QtCore.QSize(1024, 576))
        self.wdgModeSelection.setAutoFillBackground(False)
        self.wdgModeSelection.setStyleSheet("#wdgModeSelection{\n"
"    background-image:url(C:/Leon/image/background.png);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 36pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 0), stop:0.1 rgba(255, 255, 255, 100), stop:0.3 rgba(255, 255, 255, 255), stop:0.6 rgba(255, 255, 255, 230), stop:1 rgba(255, 255, 255, 50));\n"
"border:0px;\n"
"border-radius:40px;\n"
"margin:10px;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(88, 238, 255, 0), stop:0.1 rgba(88, 238, 255, 100), stop:0.3 rgba(88, 238, 255, 255), stop:0.6 rgba(88, 238, 255, 230), stop:1 rgba(88, 238, 255, 50));\n"
"}")
        self.wdgModeSelection.setObjectName("wdgModeSelection")
        self.gridLayout_23 = QtWidgets.QGridLayout(self.wdgModeSelection)
        self.gridLayout_23.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout_23.setVerticalSpacing(0)
        self.gridLayout_23.setObjectName("gridLayout_23")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem, 5, 3, 1, 1)
        self.wdgGuidance = WidgetButton(self.wdgModeSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgGuidance.sizePolicy().hasHeightForWidth())
        self.wdgGuidance.setSizePolicy(sizePolicy)
        self.wdgGuidance.setMinimumSize(QtCore.QSize(0, 200))
        self.wdgGuidance.setMaximumSize(QtCore.QSize(16777215, 200))
        self.wdgGuidance.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wdgGuidance.setStyleSheet("QWidget{\n"
"font: 32pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 0), stop:0.1 rgba(255, 255, 255, 100), stop:0.3 rgba(255, 255, 255, 255), stop:0.6 rgba(255, 255, 255, 230), stop:1 rgba(255, 255, 255, 50));\n"
"border:0px;\n"
"border-radius:40px;\n"
"padding:0px;\n"
"margin:10px;\n"
"}\n"
"\n"
"QWidget:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(88, 238, 255, 0), stop:0.1 rgba(88, 238, 255, 100), stop:0.3 rgba(88, 238, 255, 255), stop:0.6 rgba(88, 238, 255, 230), stop:1 rgba(88, 238, 255, 50));\n"
"}\n"
"\n"
"QLabel{\n"
"    margin-top:0px;\n"
"    margin-bottom:0px;\n"
"    padding:0px;\n"
"}")
        self.wdgGuidance.setObjectName("wdgGuidance")
        self.gridLayout_24 = QtWidgets.QGridLayout(self.wdgGuidance)
        self.gridLayout_24.setObjectName("gridLayout_24")
        self.label_19 = QtWidgets.QLabel(self.wdgGuidance)
        self.label_19.setStyleSheet("background:none;\n"
"font: 14pt \"Arial\";")
        self.label_19.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_24.addWidget(self.label_19, 2, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.wdgGuidance)
        self.label_20.setStyleSheet("background:none;")
        self.label_20.setObjectName("label_20")
        self.gridLayout_24.addWidget(self.label_20, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_24.addItem(spacerItem2, 3, 0, 1, 1)
        self.gridLayout_23.addWidget(self.wdgGuidance, 5, 2, 1, 1)
        self.label_title_13 = QtWidgets.QLabel(self.wdgModeSelection)
        self.label_title_13.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_13.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_13.setStyleSheet("\n"
"    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_13.setObjectName("label_title_13")
        self.gridLayout_23.addWidget(self.label_title_13, 1, 0, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_23.addItem(spacerItem3, 5, 0, 1, 1)
        self.wdgPlanning = WidgetButton(self.wdgModeSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgPlanning.sizePolicy().hasHeightForWidth())
        self.wdgPlanning.setSizePolicy(sizePolicy)
        self.wdgPlanning.setMinimumSize(QtCore.QSize(0, 200))
        self.wdgPlanning.setMaximumSize(QtCore.QSize(16777215, 200))
        self.wdgPlanning.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.wdgPlanning.setMouseTracking(False)
        self.wdgPlanning.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.wdgPlanning.setStyleSheet("QWidget{\n"
"font: 32pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 0), stop:0.1 rgba(255, 255, 255, 100), stop:0.3 rgba(255, 255, 255, 255), stop:0.6 rgba(255, 255, 255, 230), stop:1 rgba(255, 255, 255, 50));\n"
"border:0px;\n"
"border-radius:40px;\n"
"padding:0px;\n"
"margin:10px;\n"
"}\n"
"\n"
"QWidget:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(88, 238, 255, 0), stop:0.1 rgba(88, 238, 255, 100), stop:0.3 rgba(88, 238, 255, 255), stop:0.6 rgba(88, 238, 255, 230), stop:1 rgba(88, 238, 255, 50));\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    margin-top:0px;\n"
"    margin-bottom:0px;\n"
"    padding:0px;\n"
"}")
        self.wdgPlanning.setObjectName("wdgPlanning")
        self.gridLayout_25 = QtWidgets.QGridLayout(self.wdgPlanning)
        self.gridLayout_25.setObjectName("gridLayout_25")
        self.label_21 = QtWidgets.QLabel(self.wdgPlanning)
        self.label_21.setStyleSheet("background:none;\n"
"font: 14pt \"Arial\";")
        self.label_21.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout_25.addWidget(self.label_21, 2, 0, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.wdgPlanning)
        self.label_22.setStyleSheet("background:none;")
        self.label_22.setObjectName("label_22")
        self.gridLayout_25.addWidget(self.label_22, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_25.addItem(spacerItem5, 3, 0, 1, 1)
        self.gridLayout_23.addWidget(self.wdgPlanning, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_23.addItem(spacerItem6, 4, 1, 1, 2)
        self.label_subtitle_3 = QtWidgets.QLabel(self.wdgModeSelection)
        self.label_subtitle_3.setStyleSheet("    color:#eeeeee;\n"
"    font: 18pt \"Cascadia Code SemiBold\";\n"
"    margin-right:240px;")
        self.label_subtitle_3.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_subtitle_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_subtitle_3.setObjectName("label_subtitle_3")
        self.gridLayout_23.addWidget(self.label_subtitle_3, 2, 0, 1, 4)
        self.gridLayout_3.addWidget(self.wdgModeSelection, 0, 0, 1, 1)
        self.stkMain.addWidget(self.pgHome)
        self.page_loading = QtWidgets.QWidget()
        self.page_loading.setObjectName("page_loading")
        self.gridLayout_26 = QtWidgets.QGridLayout(self.page_loading)
        self.gridLayout_26.setObjectName("gridLayout_26")
        self.mainWidget = QtWidgets.QWidget(self.page_loading)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setMinimumSize(QtCore.QSize(1024, 576))
        self.mainWidget.setMaximumSize(QtCore.QSize(1024, 576))
        self.mainWidget.setAutoFillBackground(False)
        self.mainWidget.setStyleSheet("#mainWidget{\n"
"    background-image:url(C:/Leon/image/background.png);\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainWidget)
        self.gridLayout_2.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_title = QtWidgets.QLabel(self.mainWidget)
        self.label_title.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title.setStyleSheet("#label_title{\n"
"    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;\n"
"}")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 1, 1, 1)
        self.wdgProgress = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgProgress.sizePolicy().hasHeightForWidth())
        self.wdgProgress.setSizePolicy(sizePolicy)
        self.wdgProgress.setMinimumSize(QtCore.QSize(600, 96))
        self.wdgProgress.setStyleSheet("#wdgProgress{\n"
"    \n"
"background-color: rgba(120, 120, 120, 180);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255, 255, 255, 100);\n"
"    border:0px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QProgressBar::chunk[value=\"100\"]{\n"
"    background-color:rgb(0, 160, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"\n"
"QProgressBar[value=\"100\"]{\n"
"    color: rgb(255, 255, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 9pt \"Arial\";\n"
"    color:#ffffff;\n"
"}\n"
"")
        self.wdgProgress.setObjectName("wdgProgress")
        self.gridLayout = QtWidgets.QGridLayout(self.wdgProgress)
        self.gridLayout.setObjectName("gridLayout")
        self.pgbRobot = QtWidgets.QProgressBar(self.wdgProgress)
        self.pgbRobot.setStyleSheet("")
        self.pgbRobot.setMaximum(100)
        self.pgbRobot.setProperty("value", 0)
        self.pgbRobot.setAlignment(QtCore.Qt.AlignCenter)
        self.pgbRobot.setTextVisible(True)
        self.pgbRobot.setOrientation(QtCore.Qt.Horizontal)
        self.pgbRobot.setInvertedAppearance(False)
        self.pgbRobot.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.pgbRobot.setObjectName("pgbRobot")
        self.gridLayout.addWidget(self.pgbRobot, 1, 2, 1, 1)
        self.wdgCheckRobot = QtWidgets.QWidget(self.wdgProgress)
        self.wdgCheckRobot.setMinimumSize(QtCore.QSize(32, 32))
        self.wdgCheckRobot.setMaximumSize(QtCore.QSize(32, 32))
        self.wdgCheckRobot.setStyleSheet("")
        self.wdgCheckRobot.setObjectName("wdgCheckRobot")
        self.gridLayout.addWidget(self.wdgCheckRobot, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.wdgProgress)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.wdgProgress)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.wdgCheckLaser = QtWidgets.QWidget(self.wdgProgress)
        self.wdgCheckLaser.setMinimumSize(QtCore.QSize(32, 32))
        self.wdgCheckLaser.setMaximumSize(QtCore.QSize(32, 32))
        self.wdgCheckLaser.setStyleSheet("")
        self.wdgCheckLaser.setObjectName("wdgCheckLaser")
        self.gridLayout.addWidget(self.wdgCheckLaser, 2, 0, 1, 1)
        self.pgbLaser = QtWidgets.QProgressBar(self.wdgProgress)
        self.pgbLaser.setStyleSheet("")
        self.pgbLaser.setProperty("value", 0)
        self.pgbLaser.setAlignment(QtCore.Qt.AlignCenter)
        self.pgbLaser.setOrientation(QtCore.Qt.Horizontal)
        self.pgbLaser.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.pgbLaser.setObjectName("pgbLaser")
        self.gridLayout.addWidget(self.pgbLaser, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.wdgProgress, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 3, 2, 1, 1)
        self.label_subtitle = QtWidgets.QLabel(self.mainWidget)
        self.label_subtitle.setStyleSheet("    color:#eeeeee;\n"
"    font: 18pt \"Cascadia Code SemiBold\";\n"
"    margin-right:240px;")
        self.label_subtitle.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_subtitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_subtitle.setObjectName("label_subtitle")
        self.gridLayout_2.addWidget(self.label_subtitle, 1, 0, 1, 3)
        self.gridLayout_26.addWidget(self.mainWidget, 0, 0, 1, 1)
        self.stkMain.addWidget(self.page_loading)
        self.pgScene = QtWidgets.QWidget()
        self.pgScene.setObjectName("pgScene")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.pgScene)
        self.horizontalLayout_16.setContentsMargins(0, 0, -1, 0)
        self.horizontalLayout_16.setSpacing(0)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.wdgNaviBar = QtWidgets.QWidget(self.pgScene)
        self.wdgNaviBar.setMinimumSize(QtCore.QSize(200, 0))
        self.wdgNaviBar.setStyleSheet("#wdgNaviBar{\n"
"    background-color: rgb(55, 96, 125);\n"
"}\n"
"\n"
"QPushButton{\n"
"    font: 12pt \"Arial\";\n"
"    background-color:rgb(109, 247, 190);\n"
"    border-radius:5px;\n"
"    border-right:2px solid #555;\n"
"    border-bottom:2px solid #555;\n"
"    border-left:1px solid #ddd;\n"
"    border-top:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    background-color:#666;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-left:2px solid #555;\n"
"    border-top:2px solid #555;\n"
"    border-right:1px solid #ddd;\n"
"    border-bottom:1px solid #ddd;\n"
"}")
        self.wdgNaviBar.setObjectName("wdgNaviBar")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wdgNaviBar)
        self.verticalLayout.setContentsMargins(11, -1, 11, -1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btnSceneRobot = QtWidgets.QPushButton(self.wdgNaviBar)
        self.btnSceneRobot.setEnabled(False)
        self.btnSceneRobot.setMinimumSize(QtCore.QSize(146, 50))
        self.btnSceneRobot.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnSceneRobot.setStyleSheet("")
        self.btnSceneRobot.setObjectName("btnSceneRobot")
        self.verticalLayout.addWidget(self.btnSceneRobot)
        self.btnSceneLaser = QtWidgets.QPushButton(self.wdgNaviBar)
        self.btnSceneLaser.setEnabled(False)
        self.btnSceneLaser.setMinimumSize(QtCore.QSize(146, 50))
        self.btnSceneLaser.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnSceneLaser.setStyleSheet("")
        self.btnSceneLaser.setObjectName("btnSceneLaser")
        self.verticalLayout.addWidget(self.btnSceneLaser)
        self.btnSceneView = QtWidgets.QPushButton(self.wdgNaviBar)
        self.btnSceneView.setEnabled(False)
        self.btnSceneView.setMinimumSize(QtCore.QSize(146, 50))
        self.btnSceneView.setMaximumSize(QtCore.QSize(146, 16777215))
        self.btnSceneView.setStyleSheet("")
        self.btnSceneView.setObjectName("btnSceneView")
        self.verticalLayout.addWidget(self.btnSceneView)
        spacerItem10 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem10)
        self.horizontalLayout_16.addWidget(self.wdgNaviBar)
        self.stkScene = QtWidgets.QStackedWidget(self.pgScene)
        self.stkScene.setStyleSheet("#stkScene > QWidget{\n"
"    background-color:#4D84AD;\n"
"}")
        self.stkScene.setObjectName("stkScene")
        self.pgHomingCheckStep1 = QtWidgets.QWidget()
        self.pgHomingCheckStep1.setObjectName("pgHomingCheckStep1")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.pgHomingCheckStep1)
        self.gridLayout_13.setObjectName("gridLayout_13")
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem11, 0, 0, 1, 1)
        self.lblDirections = QtWidgets.QLabel(self.pgHomingCheckStep1)
        self.lblDirections.setMinimumSize(QtCore.QSize(350, 0))
        self.lblDirections.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.lblDirections.setObjectName("lblDirections")
        self.gridLayout_13.addWidget(self.lblDirections, 0, 2, 1, 1)
        self.wdgHomingPlatform = QtWidgets.QWidget(self.pgHomingCheckStep1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgHomingPlatform.sizePolicy().hasHeightForWidth())
        self.wdgHomingPlatform.setSizePolicy(sizePolicy)
        self.wdgHomingPlatform.setMinimumSize(QtCore.QSize(640, 490))
        self.wdgHomingPlatform.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wdgHomingPlatform.setStyleSheet("background-image:url(C:/Leon/image/robot.png)")
        self.wdgHomingPlatform.setObjectName("wdgHomingPlatform")
        self.gridLayout_13.addWidget(self.wdgHomingPlatform, 0, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_13.addItem(spacerItem12, 0, 3, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.btnNext_confirmHomingStep1 = QtWidgets.QPushButton(self.pgHomingCheckStep1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_confirmHomingStep1.sizePolicy().hasHeightForWidth())
        self.btnNext_confirmHomingStep1.setSizePolicy(sizePolicy)
        self.btnNext_confirmHomingStep1.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_confirmHomingStep1.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_confirmHomingStep1.setObjectName("btnNext_confirmHomingStep1")
        self.horizontalLayout_2.addWidget(self.btnNext_confirmHomingStep1)
        self.gridLayout_13.addLayout(self.horizontalLayout_2, 3, 0, 1, 4)
        self.stkScene.addWidget(self.pgHomingCheckStep1)
        self.pgHomingCheckStep2 = QtWidgets.QWidget()
        self.pgHomingCheckStep2.setObjectName("pgHomingCheckStep2")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.pgHomingCheckStep2)
        self.gridLayout_14.setObjectName("gridLayout_14")
        spacerItem13 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem13, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.pgHomingCheckStep2)
        self.label_7.setMinimumSize(QtCore.QSize(350, 0))
        self.label_7.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_7.setObjectName("label_7")
        self.gridLayout_14.addWidget(self.label_7, 0, 2, 1, 1)
        self.widget = QtWidgets.QWidget(self.pgHomingCheckStep2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(640, 490))
        self.widget.setStyleSheet("background-image:url(C:/Leon/image/robot.png)")
        self.widget.setObjectName("widget")
        self.gridLayout_14.addWidget(self.widget, 0, 1, 1, 1)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_14.addItem(spacerItem14, 0, 3, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnNext_confirmHomingStep2 = QtWidgets.QPushButton(self.pgHomingCheckStep2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_confirmHomingStep2.sizePolicy().hasHeightForWidth())
        self.btnNext_confirmHomingStep2.setSizePolicy(sizePolicy)
        self.btnNext_confirmHomingStep2.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_confirmHomingStep2.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_confirmHomingStep2.setObjectName("btnNext_confirmHomingStep2")
        self.horizontalLayout_3.addWidget(self.btnNext_confirmHomingStep2)
        self.gridLayout_14.addLayout(self.horizontalLayout_3, 3, 0, 1, 4)
        self.stkScene.addWidget(self.pgHomingCheckStep2)
        self.pgRobotRegSphere = QtWidgets.QWidget()
        self.pgRobotRegSphere.setObjectName("pgRobotRegSphere")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.pgRobotRegSphere)
        self.gridLayout_9.setObjectName("gridLayout_9")
        spacerItem15 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem15, 1, 0, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem16, 1, 3, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.pgRobotRegSphere)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setMinimumSize(QtCore.QSize(640, 490))
        self.widget_2.setStyleSheet("background-image:url(C:/Leon/image/robot.png)")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout_9.addWidget(self.widget_2, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.pgRobotRegSphere)
        self.label_8.setMinimumSize(QtCore.QSize(350, 0))
        self.label_8.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_8.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_8.setObjectName("label_8")
        self.gridLayout_9.addWidget(self.label_8, 1, 2, 1, 1)
        self.label_title_3 = QtWidgets.QLabel(self.pgRobotRegSphere)
        self.label_title_3.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_3.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_3.setObjectName("label_title_3")
        self.gridLayout_9.addWidget(self.label_title_3, 0, 0, 1, 4)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.btnNext_settingRobot = QtWidgets.QPushButton(self.pgRobotRegSphere)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_settingRobot.sizePolicy().hasHeightForWidth())
        self.btnNext_settingRobot.setSizePolicy(sizePolicy)
        self.btnNext_settingRobot.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_settingRobot.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_settingRobot.setObjectName("btnNext_settingRobot")
        self.horizontalLayout_4.addWidget(self.btnNext_settingRobot)
        self.gridLayout_9.addLayout(self.horizontalLayout_4, 3, 0, 1, 4)
        self.stkScene.addWidget(self.pgRobotRegSphere)
        self.pgRobotSupportArm = QtWidgets.QWidget()
        self.pgRobotSupportArm.setObjectName("pgRobotSupportArm")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.pgRobotSupportArm)
        self.gridLayout_15.setObjectName("gridLayout_15")
        spacerItem17 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem17, 1, 0, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.pgRobotSupportArm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setMinimumSize(QtCore.QSize(640, 490))
        self.widget_3.setStyleSheet("background-image:url(C:/Leon/image/robot.png)")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout_15.addWidget(self.widget_3, 1, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.pgRobotSupportArm)
        self.label_9.setMinimumSize(QtCore.QSize(350, 0))
        self.label_9.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_9.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_9.setObjectName("label_9")
        self.gridLayout_15.addWidget(self.label_9, 1, 2, 1, 1)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_15.addItem(spacerItem18, 1, 3, 1, 1)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.btnNext_settingRobot_2 = QtWidgets.QPushButton(self.pgRobotSupportArm)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_settingRobot_2.sizePolicy().hasHeightForWidth())
        self.btnNext_settingRobot_2.setSizePolicy(sizePolicy)
        self.btnNext_settingRobot_2.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_settingRobot_2.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_settingRobot_2.setObjectName("btnNext_settingRobot_2")
        self.horizontalLayout_5.addWidget(self.btnNext_settingRobot_2)
        self.gridLayout_15.addLayout(self.horizontalLayout_5, 2, 0, 1, 4)
        self.label_title_7 = QtWidgets.QLabel(self.pgRobotSupportArm)
        self.label_title_7.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_7.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_7.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_7.setObjectName("label_title_7")
        self.gridLayout_15.addWidget(self.label_title_7, 0, 0, 1, 4)
        self.stkScene.addWidget(self.pgRobotSupportArm)
        self.pgLaser = QtWidgets.QWidget()
        self.pgLaser.setObjectName("pgLaser")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.pgLaser)
        self.gridLayout_10.setObjectName("gridLayout_10")
        spacerItem19 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem19, 1, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.pgLaser)
        self.label_11.setMinimumSize(QtCore.QSize(350, 0))
        self.label_11.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_11.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_11.setObjectName("label_11")
        self.gridLayout_10.addWidget(self.label_11, 1, 2, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.pgLaser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(640, 490))
        self.widget_4.setStyleSheet("background-image:url(C:/Leon/image/robot.png)")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_10.addWidget(self.widget_4, 1, 1, 1, 1)
        spacerItem20 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem20, 1, 3, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnNext_settingLaser = QtWidgets.QPushButton(self.pgLaser)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_settingLaser.sizePolicy().hasHeightForWidth())
        self.btnNext_settingLaser.setSizePolicy(sizePolicy)
        self.btnNext_settingLaser.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_settingLaser.setMaximumSize(QtCore.QSize(324, 16777215))
        self.btnNext_settingLaser.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_settingLaser.setObjectName("btnNext_settingLaser")
        self.horizontalLayout.addWidget(self.btnNext_settingLaser)
        self.gridLayout_10.addLayout(self.horizontalLayout, 2, 0, 1, 4)
        self.label_title_4 = QtWidgets.QLabel(self.pgLaser)
        self.label_title_4.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_4.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_4.setObjectName("label_title_4")
        self.gridLayout_10.addWidget(self.label_title_4, 0, 0, 1, 4)
        self.stkScene.addWidget(self.pgLaser)
        self.pgLaserAdjust = QtWidgets.QWidget()
        self.pgLaserAdjust.setObjectName("pgLaserAdjust")
        self.gridLayout_16 = QtWidgets.QGridLayout(self.pgLaserAdjust)
        self.gridLayout_16.setObjectName("gridLayout_16")
        self.label_10 = QtWidgets.QLabel(self.pgLaserAdjust)
        self.label_10.setMinimumSize(QtCore.QSize(350, 0))
        self.label_10.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_10.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_10.setObjectName("label_10")
        self.gridLayout_16.addWidget(self.label_10, 1, 1, 1, 1)
        self.label_title_8 = QtWidgets.QLabel(self.pgLaserAdjust)
        self.label_title_8.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_8.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_8.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_8.setObjectName("label_title_8")
        self.gridLayout_16.addWidget(self.label_title_8, 0, 0, 1, 2)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.btnNext_settingLaser_2 = QtWidgets.QPushButton(self.pgLaserAdjust)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_settingLaser_2.sizePolicy().hasHeightForWidth())
        self.btnNext_settingLaser_2.setSizePolicy(sizePolicy)
        self.btnNext_settingLaser_2.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_settingLaser_2.setMaximumSize(QtCore.QSize(324, 16777215))
        self.btnNext_settingLaser_2.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_settingLaser_2.setObjectName("btnNext_settingLaser_2")
        self.horizontalLayout_6.addWidget(self.btnNext_settingLaser_2)
        self.gridLayout_16.addLayout(self.horizontalLayout_6, 4, 0, 1, 2)
        self.wdgLaserOk = QtWidgets.QWidget(self.pgLaserAdjust)
        self.wdgLaserOk.setStyleSheet("border-image:url(C:/Leon/image/laserOK.jpg)")
        self.wdgLaserOk.setObjectName("wdgLaserOk")
        self.gridLayout_16.addWidget(self.wdgLaserOk, 2, 1, 1, 1)
        self.wdgLaserFail = QtWidgets.QWidget(self.pgLaserAdjust)
        self.wdgLaserFail.setStyleSheet("border-image:url(C:/Leon/image/laserFail.jpg)")
        self.wdgLaserFail.setObjectName("wdgLaserFail")
        self.gridLayout_16.addWidget(self.wdgLaserFail, 3, 1, 1, 1)
        self.wdgLaserPlot = QtWidgets.QWidget(self.pgLaserAdjust)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgLaserPlot.sizePolicy().hasHeightForWidth())
        self.wdgLaserPlot.setSizePolicy(sizePolicy)
        self.wdgLaserPlot.setMinimumSize(QtCore.QSize(1000, 500))
        self.wdgLaserPlot.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wdgLaserPlot.setObjectName("wdgLaserPlot")
        self.gridLayout_16.addWidget(self.wdgLaserPlot, 1, 0, 3, 1)
        self.stkScene.addWidget(self.pgLaserAdjust)
        self.pgModelBuilding = QtWidgets.QWidget()
        self.pgModelBuilding.setStyleSheet("")
        self.pgModelBuilding.setObjectName("pgModelBuilding")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.pgModelBuilding)
        self.gridLayout_11.setObjectName("gridLayout_11")
        spacerItem21 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem21, 1, 0, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.pgModelBuilding)
        self.label_12.setMinimumSize(QtCore.QSize(350, 0))
        self.label_12.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_12.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_12.setObjectName("label_12")
        self.gridLayout_11.addWidget(self.label_12, 1, 2, 1, 1)
        self.wdgIntraCT = QtWidgets.QWidget(self.pgModelBuilding)
        self.wdgIntraCT.setMinimumSize(QtCore.QSize(1186, 403))
        self.wdgIntraCT.setMaximumSize(QtCore.QSize(600, 450))
        self.wdgIntraCT.setStyleSheet("border-image:url(C:/Leon/image/model_building.png);")
        self.wdgIntraCT.setObjectName("wdgIntraCT")
        self.gridLayout_11.addWidget(self.wdgIntraCT, 1, 1, 1, 1)
        spacerItem22 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_11.addItem(spacerItem22, 1, 3, 1, 1)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem23 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem23)
        self.btnNext_scanCT = QtWidgets.QPushButton(self.pgModelBuilding)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_scanCT.sizePolicy().hasHeightForWidth())
        self.btnNext_scanCT.setSizePolicy(sizePolicy)
        self.btnNext_scanCT.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_scanCT.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_scanCT.setObjectName("btnNext_scanCT")
        self.horizontalLayout_7.addWidget(self.btnNext_scanCT)
        spacerItem24 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem24)
        self.gridLayout_11.addLayout(self.horizontalLayout_7, 2, 0, 1, 4)
        self.label_title_5 = QtWidgets.QLabel(self.pgModelBuilding)
        self.label_title_5.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_5.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_5.setObjectName("label_title_5")
        self.gridLayout_11.addWidget(self.label_title_5, 0, 0, 1, 4)
        self.stkScene.addWidget(self.pgModelBuilding)
        self.pgStartCT = QtWidgets.QWidget()
        self.pgStartCT.setObjectName("pgStartCT")
        self.gridLayout_18 = QtWidgets.QGridLayout(self.pgStartCT)
        self.gridLayout_18.setObjectName("gridLayout_18")
        self.label_13 = QtWidgets.QLabel(self.pgStartCT)
        self.label_13.setMinimumSize(QtCore.QSize(350, 0))
        self.label_13.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_13.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_13.setObjectName("label_13")
        self.gridLayout_18.addWidget(self.label_13, 1, 2, 1, 1)
        self.label_title_10 = QtWidgets.QLabel(self.pgStartCT)
        self.label_title_10.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_10.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_10.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_10.setObjectName("label_title_10")
        self.gridLayout_18.addWidget(self.label_title_10, 0, 1, 1, 2)
        spacerItem25 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem25, 1, 0, 1, 1)
        self.wdgIntraCT_2 = QtWidgets.QWidget(self.pgStartCT)
        self.wdgIntraCT_2.setMinimumSize(QtCore.QSize(600, 450))
        self.wdgIntraCT_2.setMaximumSize(QtCore.QSize(600, 450))
        self.wdgIntraCT_2.setStyleSheet("border-image:url(C:/Leon/image/IntraCT.jpg);")
        self.wdgIntraCT_2.setObjectName("wdgIntraCT_2")
        self.gridLayout_18.addWidget(self.wdgIntraCT_2, 1, 1, 1, 1)
        spacerItem26 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_18.addItem(spacerItem26, 1, 3, 1, 1)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.btnNext_scanCT_3 = QtWidgets.QPushButton(self.pgStartCT)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_scanCT_3.sizePolicy().hasHeightForWidth())
        self.btnNext_scanCT_3.setSizePolicy(sizePolicy)
        self.btnNext_scanCT_3.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_scanCT_3.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_scanCT_3.setObjectName("btnNext_scanCT_3")
        self.horizontalLayout_9.addWidget(self.btnNext_scanCT_3)
        self.gridLayout_18.addLayout(self.horizontalLayout_9, 2, 0, 1, 4)
        self.stkScene.addWidget(self.pgStartCT)
        self.pgModelFinish = QtWidgets.QWidget()
        self.pgModelFinish.setObjectName("pgModelFinish")
        self.gridLayout_17 = QtWidgets.QGridLayout(self.pgModelFinish)
        self.gridLayout_17.setObjectName("gridLayout_17")
        spacerItem27 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem27, 1, 0, 1, 1)
        self.widget_5 = QtWidgets.QWidget(self.pgModelFinish)
        self.widget_5.setMinimumSize(QtCore.QSize(1186, 403))
        self.widget_5.setMaximumSize(QtCore.QSize(1186, 403))
        self.widget_5.setStyleSheet("background-image:url(C:/Leon/image/model_building.png);")
        self.widget_5.setObjectName("widget_5")
        self.wdgCheck = QtWidgets.QWidget(self.widget_5)
        self.wdgCheck.setGeometry(QtCore.QRect(460, 150, 256, 256))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgCheck.sizePolicy().hasHeightForWidth())
        self.wdgCheck.setSizePolicy(sizePolicy)
        self.wdgCheck.setMinimumSize(QtCore.QSize(256, 256))
        self.wdgCheck.setMaximumSize(QtCore.QSize(256, 256))
        self.wdgCheck.setStyleSheet("background-image:url(C:/Leon/image/check-mark.png)")
        self.wdgCheck.setObjectName("wdgCheck")
        self.gridLayout_17.addWidget(self.widget_5, 1, 1, 1, 1)
        spacerItem28 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_17.addItem(spacerItem28, 1, 2, 1, 1)
        self.label_title_9 = QtWidgets.QLabel(self.pgModelFinish)
        self.label_title_9.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_9.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_9.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_9.setObjectName("label_title_9")
        self.gridLayout_17.addWidget(self.label_title_9, 0, 0, 1, 3)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        spacerItem29 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem29)
        self.btnNext_scanCT_2 = QtWidgets.QPushButton(self.pgModelFinish)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_scanCT_2.sizePolicy().hasHeightForWidth())
        self.btnNext_scanCT_2.setSizePolicy(sizePolicy)
        self.btnNext_scanCT_2.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_scanCT_2.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_scanCT_2.setObjectName("btnNext_scanCT_2")
        self.horizontalLayout_8.addWidget(self.btnNext_scanCT_2)
        spacerItem30 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem30)
        self.gridLayout_17.addLayout(self.horizontalLayout_8, 2, 0, 1, 3)
        self.stkScene.addWidget(self.pgModelFinish)
        self.pgImportDicom = QtWidgets.QWidget()
        self.pgImportDicom.setObjectName("pgImportDicom")
        self.gridLayout_20 = QtWidgets.QGridLayout(self.pgImportDicom)
        self.gridLayout_20.setObjectName("gridLayout_20")
        self.label_title_12 = QtWidgets.QLabel(self.pgImportDicom)
        self.label_title_12.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_12.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_12.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_12.setObjectName("label_title_12")
        self.gridLayout_20.addWidget(self.label_title_12, 0, 0, 1, 1)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        spacerItem31 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem31)
        self.btnFromUSB = QtWidgets.QPushButton(self.pgImportDicom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFromUSB.sizePolicy().hasHeightForWidth())
        self.btnFromUSB.setSizePolicy(sizePolicy)
        self.btnFromUSB.setMinimumSize(QtCore.QSize(300, 300))
        self.btnFromUSB.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnFromUSB.setObjectName("btnFromUSB")
        self.horizontalLayout_11.addWidget(self.btnFromUSB)
        self.btnFromCD = QtWidgets.QPushButton(self.pgImportDicom)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnFromCD.sizePolicy().hasHeightForWidth())
        self.btnFromCD.setSizePolicy(sizePolicy)
        self.btnFromCD.setMinimumSize(QtCore.QSize(300, 300))
        self.btnFromCD.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnFromCD.setObjectName("btnFromCD")
        self.horizontalLayout_11.addWidget(self.btnFromCD)
        spacerItem32 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_11.addItem(spacerItem32)
        self.gridLayout_20.addLayout(self.horizontalLayout_11, 1, 0, 1, 1)
        self.stkScene.addWidget(self.pgImportDicom)
        self.pgDicomList = QtWidgets.QWidget()
        self.pgDicomList.setObjectName("pgDicomList")
        self.gridLayout_12 = QtWidgets.QGridLayout(self.pgDicomList)
        self.gridLayout_12.setObjectName("gridLayout_12")
        self.label_title_6 = QtWidgets.QLabel(self.pgDicomList)
        self.label_title_6.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_6.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_6.setObjectName("label_title_6")
        self.gridLayout_12.addWidget(self.label_title_6, 0, 0, 1, 1)
        self.treeDicomFilter = QtWidgets.QTreeView(self.pgDicomList)
        self.treeDicomFilter.setMaximumSize(QtCore.QSize(16777215, 200))
        self.treeDicomFilter.setStyleSheet("font: 12pt \"Arial\";")
        self.treeDicomFilter.setObjectName("treeDicomFilter")
        self.gridLayout_12.addWidget(self.treeDicomFilter, 1, 0, 1, 1)
        self.treeDicom = QtWidgets.QTreeView(self.pgDicomList)
        self.treeDicom.setStyleSheet("font: 12pt \"Arial\";")
        self.treeDicom.setObjectName("treeDicom")
        self.gridLayout_12.addWidget(self.treeDicom, 2, 0, 1, 1)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        spacerItem33 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem33)
        self.pushButton_7 = QtWidgets.QPushButton(self.pgDicomList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_7.setMaximumSize(QtCore.QSize(324, 16777215))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.horizontalLayout_12.addWidget(self.pushButton_7)
        self.btnImport = QtWidgets.QPushButton(self.pgDicomList)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnImport.sizePolicy().hasHeightForWidth())
        self.btnImport.setSizePolicy(sizePolicy)
        self.btnImport.setMinimumSize(QtCore.QSize(324, 150))
        self.btnImport.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnImport.setObjectName("btnImport")
        self.horizontalLayout_12.addWidget(self.btnImport)
        spacerItem34 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem34)
        self.gridLayout_12.addLayout(self.horizontalLayout_12, 3, 0, 1, 1)
        self.stkScene.addWidget(self.pgDicomList)
        self.pgImageView = QtWidgets.QWidget()
        self.pgImageView.setObjectName("pgImageView")
        self.gridLayout_22 = QtWidgets.QGridLayout(self.pgImageView)
        self.gridLayout_22.setSpacing(0)
        self.gridLayout_22.setObjectName("gridLayout_22")
        self.widget_7 = QtWidgets.QWidget(self.pgImageView)
        self.widget_7.setMinimumSize(QtCore.QSize(0, 0))
        self.widget_7.setStyleSheet("image:url(C:/Leon/image/trajectory_check.png);\n"
"image-position:top")
        self.widget_7.setObjectName("widget_7")
        self.gridLayout_22.addWidget(self.widget_7, 1, 0, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.pgImageView)
        self.label_18.setMinimumSize(QtCore.QSize(0, 40))
        self.label_18.setMaximumSize(QtCore.QSize(16777215, 40))
        self.label_18.setText("")
        self.label_18.setObjectName("label_18")
        self.gridLayout_22.addWidget(self.label_18, 0, 0, 1, 1)
        self.tabWidget = QtWidgets.QTabWidget(self.pgImageView)
        self.tabWidget.setMinimumSize(QtCore.QSize(300, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(300, 16777215))
        self.tabWidget.setStyleSheet("QTabWidget QWidget{\n"
"background-color: rgb(93, 161, 209);\n"
"}\n"
"\n"
"QTabWidget > QWidget{\n"
"background-color:rgba(0, 0, 0, 0);\n"
"}\n"
"\n"
"\n"
"\n"
"QTabWidget::pane{\n"
"background-color:#666;\n"
"}\n"
"\n"
"QTabWidget QPushButton{\n"
"    background-color:rgb(109, 190, 247);\n"
"    font: 14px Arial;\n"
"    color:#ffffff;\n"
"}\n"
"\n"
"\n"
"QTabBar::tab{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"                                stop:0 rgba(77, 132, 173, 255), stop:1 rgba(109, 190, 247, 255));\n"
"}\n"
"\n"
"QTabBar::tab:top{\n"
"min-width:150px;\n"
"height:40px;\n"
"border-top-left-radius:40px;\n"
"border-top-right-radius:40px;\n"
"border-width:1px;\n"
"}\n"
"\n"
"QTabBar::tab:hover {\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"                        stop:0 rgba(139, 220, 255, 255),\n"
"                         stop:1 rgba(109, 190, 247, 255));\n"
"}\n"
"\n"
"QTabBar::tab:selected{\n"
"    background:  qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, \n"
"                        stop:0 rgba(109, 190, 247, 255),\n"
"                         stop:1 rgba(0, 255, 255, 255));\n"
"}\n"
"\n"
"")
        self.tabWidget.setObjectName("tabWidget")
        self.tabPlanning = QtWidgets.QWidget()
        self.tabPlanning.setObjectName("tabPlanning")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.tabPlanning)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.toolBox = QtWidgets.QToolBox(self.tabPlanning)
        self.toolBox.setStyleSheet("QToolBox{\n"
"background-color: rgb(93, 161, 209);\n"
"}\n"
"\n"
"QToolBox QWidget{\n"
"background-color: rgb(93, 161, 209);\n"
"}\n"
"\n"
"QToolBox::tab{\n"
"    background-color: rgb(109, 190, 247);\n"
"}\n"
"\n"
"QToolBox QPushButton{\n"
"    background-color:rgb(109, 190, 247);\n"
"    border-top:1px solid #ddd;\n"
"    border-left:1px solid #ddd;\n"
"    border-bottom:2px solid #444;\n"
"    border-right:2px solid #444;\n"
"}\n"
"\n"
"QToolBox QPushButton:pressed{\n"
"    border-bottom:1px solid #ddd;\n"
"    border-right:1px solid #ddd;\n"
"    border-top:2px solid #444;\n"
"    border-left:2px solid #444;\n"
"}\n"
"")
        self.toolBox.setObjectName("toolBox")
        self.pgTrajectory = QtWidgets.QWidget()
        self.pgTrajectory.setGeometry(QtCore.QRect(0, 0, 156, 142))
        self.pgTrajectory.setObjectName("pgTrajectory")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.pgTrajectory)
        self.verticalLayout_3.setContentsMargins(-1, 11, -1, -1)
        self.verticalLayout_3.setSpacing(7)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.pushButton_2 = QtWidgets.QPushButton(self.pgTrajectory)
        self.pushButton_2.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_2.setObjectName("pushButton_2")
        self.horizontalLayout_14.addWidget(self.pushButton_2)
        self.pushButton_3 = QtWidgets.QPushButton(self.pgTrajectory)
        self.pushButton_3.setMinimumSize(QtCore.QSize(0, 40))
        self.pushButton_3.setObjectName("pushButton_3")
        self.horizontalLayout_14.addWidget(self.pushButton_3)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.label_15 = QtWidgets.QLabel(self.pgTrajectory)
        self.label_15.setObjectName("label_15")
        self.verticalLayout_3.addWidget(self.label_15)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.pushButton_4 = QtWidgets.QPushButton(self.pgTrajectory)
        self.pushButton_4.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_4.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_4.setStyleSheet("border-top-left-radius:20px;\n"
"border-bottom-left-radius:20px;\n"
"font: 12px Arial;")
        self.pushButton_4.setObjectName("pushButton_4")
        self.horizontalLayout_13.addWidget(self.pushButton_4)
        self.horizontalSlider = QtWidgets.QSlider(self.pgTrajectory)
        self.horizontalSlider.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider.setObjectName("horizontalSlider")
        self.horizontalLayout_13.addWidget(self.horizontalSlider)
        self.pushButton_5 = QtWidgets.QPushButton(self.pgTrajectory)
        self.pushButton_5.setMinimumSize(QtCore.QSize(50, 40))
        self.pushButton_5.setMaximumSize(QtCore.QSize(50, 16777215))
        self.pushButton_5.setStyleSheet("border-top-right-radius:20px;\n"
"border-bottom-right-radius:20px;\n"
"font: 12px Arial;")
        self.pushButton_5.setObjectName("pushButton_5")
        self.horizontalLayout_13.addWidget(self.pushButton_5)
        self.verticalLayout_3.addLayout(self.horizontalLayout_13)
        spacerItem35 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_3.addItem(spacerItem35)
        self.toolBox.addItem(self.pgTrajectory, "")
        self.pgImage = QtWidgets.QWidget()
        self.pgImage.setGeometry(QtCore.QRect(0, 0, 109, 124))
        self.pgImage.setObjectName("pgImage")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pgImage)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_16 = QtWidgets.QLabel(self.pgImage)
        self.label_16.setObjectName("label_16")
        self.verticalLayout_2.addWidget(self.label_16)
        self.horizontalSlider_2 = QtWidgets.QSlider(self.pgImage)
        self.horizontalSlider_2.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_2.setObjectName("horizontalSlider_2")
        self.verticalLayout_2.addWidget(self.horizontalSlider_2)
        self.label_17 = QtWidgets.QLabel(self.pgImage)
        self.label_17.setObjectName("label_17")
        self.verticalLayout_2.addWidget(self.label_17)
        self.horizontalSlider_3 = QtWidgets.QSlider(self.pgImage)
        self.horizontalSlider_3.setOrientation(QtCore.Qt.Horizontal)
        self.horizontalSlider_3.setObjectName("horizontalSlider_3")
        self.verticalLayout_2.addWidget(self.horizontalSlider_3)
        spacerItem36 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_2.addItem(spacerItem36)
        self.toolBox.addItem(self.pgImage, "")
        self.verticalLayout_4.addWidget(self.toolBox)
        self.tabWidget.addTab(self.tabPlanning, "")
        self.tabGuidance = QtWidgets.QWidget()
        self.tabGuidance.setObjectName("tabGuidance")
        self.gridLayout_21 = QtWidgets.QGridLayout(self.tabGuidance)
        self.gridLayout_21.setObjectName("gridLayout_21")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.pushButton_6 = QtWidgets.QPushButton(self.tabGuidance)
        self.pushButton_6.setMinimumSize(QtCore.QSize(256, 256))
        self.pushButton_6.setMaximumSize(QtCore.QSize(256, 256))
        self.pushButton_6.setAutoFillBackground(False)
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"background-image:url(C:/Leon/image/stop-sign.png);\n"
"background-color: rgb(93, 161, 209);\n"
"border-left:1px solid #ccc;\n"
"border-top:1px solid #ccc;\n"
"border-right:2px solid #555;\n"
"border-bottom:2px solid #555;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"/*margin-top:2px;\n"
"margin-left:1px;*/\n"
"border-left:2px solid #555;\n"
"border-top:2px solid #555;\n"
"border-right:1px solid #ccc;\n"
"border-bottom:1px solid #ccc;\n"
"}")
        self.pushButton_6.setText("")
        self.pushButton_6.setObjectName("pushButton_6")
        self.horizontalLayout_15.addWidget(self.pushButton_6)
        self.gridLayout_21.addLayout(self.horizontalLayout_15, 0, 0, 1, 2)
        self.pushButton = QtWidgets.QPushButton(self.tabGuidance)
        self.pushButton.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_21.addWidget(self.pushButton, 1, 0, 1, 1)
        self.pushButton_8 = QtWidgets.QPushButton(self.tabGuidance)
        self.pushButton_8.setMinimumSize(QtCore.QSize(0, 50))
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_21.addWidget(self.pushButton_8, 1, 1, 1, 1)
        spacerItem37 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_21.addItem(spacerItem37, 2, 0, 1, 1)
        self.tabWidget.addTab(self.tabGuidance, "")
        self.gridLayout_22.addWidget(self.tabWidget, 0, 1, 2, 1)
        self.stkScene.addWidget(self.pgImageView)
        self.pgInstallAdaptor = QtWidgets.QWidget()
        self.pgInstallAdaptor.setObjectName("pgInstallAdaptor")
        self.gridLayout_19 = QtWidgets.QGridLayout(self.pgInstallAdaptor)
        self.gridLayout_19.setObjectName("gridLayout_19")
        self.widget_6 = QtWidgets.QWidget(self.pgInstallAdaptor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_6.sizePolicy().hasHeightForWidth())
        self.widget_6.setSizePolicy(sizePolicy)
        self.widget_6.setMinimumSize(QtCore.QSize(640, 490))
        self.widget_6.setStyleSheet("background-image:url(C:/Leon/image/robot.png)")
        self.widget_6.setObjectName("widget_6")
        self.gridLayout_19.addWidget(self.widget_6, 1, 1, 1, 1)
        spacerItem38 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem38, 1, 0, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.pgInstallAdaptor)
        self.label_14.setMinimumSize(QtCore.QSize(350, 0))
        self.label_14.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.label_14.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label_14.setObjectName("label_14")
        self.gridLayout_19.addWidget(self.label_14, 1, 2, 1, 1)
        spacerItem39 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_19.addItem(spacerItem39, 1, 3, 1, 1)
        self.label_title_11 = QtWidgets.QLabel(self.pgInstallAdaptor)
        self.label_title_11.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_11.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_11.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_11.setObjectName("label_title_11")
        self.gridLayout_19.addWidget(self.label_title_11, 0, 0, 1, 4)
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.btnNext_scanCT_4 = QtWidgets.QPushButton(self.pgInstallAdaptor)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnNext_scanCT_4.sizePolicy().hasHeightForWidth())
        self.btnNext_scanCT_4.setSizePolicy(sizePolicy)
        self.btnNext_scanCT_4.setMinimumSize(QtCore.QSize(324, 150))
        self.btnNext_scanCT_4.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnNext_scanCT_4.setObjectName("btnNext_scanCT_4")
        self.horizontalLayout_10.addWidget(self.btnNext_scanCT_4)
        self.gridLayout_19.addLayout(self.horizontalLayout_10, 2, 0, 1, 4)
        self.stkScene.addWidget(self.pgInstallAdaptor)
        self.horizontalLayout_16.addWidget(self.stkScene)
        self.stkMain.addWidget(self.pgScene)
        self.gridLayout_4.addWidget(self.stkMain, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1920, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stkMain.setCurrentIndex(2)
        self.stkScene.setCurrentIndex(8)
        self.tabWidget.setCurrentIndex(0)
        self.toolBox.setCurrentIndex(0)
        self.btnNext_settingRobot.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_confirmHomingStep2.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_confirmHomingStep1.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_settingRobot_2.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_settingLaser.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_settingLaser_2.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_scanCT.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_scanCT_3.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_scanCT_2.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnNext_scanCT_4.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnFromCD.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnFromUSB.clicked.connect(MainWindow.NextScene) # type: ignore
        self.btnImport.clicked.connect(MainWindow.NextScene) # type: ignore
        self.pushButton_7.clicked.connect(MainWindow.BackScene) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_19.setText(_translate("MainWindow", "intra-operative"))
        self.label_20.setText(_translate("MainWindow", "Guidance"))
        self.label_title_13.setText(_translate("MainWindow", "AitherBot"))
        self.label_21.setText(_translate("MainWindow", "pre-operative"))
        self.label_22.setText(_translate("MainWindow", "Planning"))
        self.label_subtitle_3.setText(_translate("MainWindow", "Lung Surgical Robotic"))
        self.label_title.setText(_translate("MainWindow", "AitherBot"))
        self.label.setText(_translate("MainWindow", "Robot System"))
        self.label_2.setText(_translate("MainWindow", "Motion Tracker"))
        self.label_subtitle.setText(_translate("MainWindow", "Lung Surgical Robotic"))
        self.btnSceneRobot.setText(_translate("MainWindow", "Robot Setting"))
        self.btnSceneLaser.setText(_translate("MainWindow", "Laser Setting"))
        self.btnSceneView.setText(_translate("MainWindow", "Image View"))
        self.lblDirections.setText(_translate("MainWindow", "Please setup robot \n"
"on Homing Platform"))
        self.btnNext_confirmHomingStep1.setText(_translate("MainWindow", "Confirm"))
        self.label_7.setText(_translate("MainWindow", "Keep space around \n"
" robotic arm clear"))
        self.btnNext_confirmHomingStep2.setText(_translate("MainWindow", "Confirm"))
        self.label_8.setText(_translate("MainWindow", "Setup registration sphere"))
        self.label_title_3.setText(_translate("MainWindow", "Setting robot"))
        self.btnNext_settingRobot.setText(_translate("MainWindow", "Confirm"))
        self.label_9.setText(_translate("MainWindow", "Install the robotic arm\n"
" on the support arm"))
        self.btnNext_settingRobot_2.setText(_translate("MainWindow", "Confirm"))
        self.label_title_7.setText(_translate("MainWindow", "Setting robot"))
        self.label_11.setText(_translate("MainWindow", "Setup Laser"))
        self.btnNext_settingLaser.setText(_translate("MainWindow", "Confirm"))
        self.label_title_4.setText(_translate("MainWindow", "Setting Laser"))
        self.label_10.setText(_translate("MainWindow", "make sure the line\n"
" in the center"))
        self.label_title_8.setText(_translate("MainWindow", "Setting Laser"))
        self.btnNext_settingLaser_2.setText(_translate("MainWindow", "Confirm"))
        self.label_12.setText(_translate("MainWindow", "Start build model"))
        self.btnNext_scanCT.setText(_translate("MainWindow", "Confirm"))
        self.label_title_5.setText(_translate("MainWindow", "Breath Model Building"))
        self.label_13.setText(_translate("MainWindow", "Start CT scan"))
        self.label_title_10.setText(_translate("MainWindow", "Intra-op CT Scan"))
        self.btnNext_scanCT_3.setText(_translate("MainWindow", "Confirm"))
        self.label_title_9.setText(_translate("MainWindow", "Model Building Finished"))
        self.btnNext_scanCT_2.setText(_translate("MainWindow", "Confirm"))
        self.label_title_12.setText(_translate("MainWindow", "Select Dicom Source"))
        self.btnFromUSB.setText(_translate("MainWindow", "USB"))
        self.btnFromCD.setText(_translate("MainWindow", "CD ROM"))
        self.label_title_6.setText(_translate("MainWindow", "Import CT"))
        self.pushButton_7.setText(_translate("MainWindow", "Back"))
        self.btnImport.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_2.setText(_translate("MainWindow", "Set Entry"))
        self.pushButton_3.setText(_translate("MainWindow", "SetTarget"))
        self.label_15.setText(_translate("MainWindow", "Trajectory"))
        self.pushButton_4.setText(_translate("MainWindow", "Entry"))
        self.pushButton_5.setText(_translate("MainWindow", "Target"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgTrajectory), _translate("MainWindow", "Trajectory"))
        self.label_16.setText(_translate("MainWindow", "Window Level"))
        self.label_17.setText(_translate("MainWindow", "Window Width"))
        self.toolBox.setItemText(self.toolBox.indexOf(self.pgImage), _translate("MainWindow", "Image"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabPlanning), _translate("MainWindow", "Planning"))
        self.pushButton.setText(_translate("MainWindow", "Drive To Trajectory"))
        self.pushButton_8.setText(_translate("MainWindow", "Return"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabGuidance), _translate("MainWindow", "Guidance"))
        self.label_14.setText(_translate("MainWindow", "Make sure the adapter \n"
"is tightened securely"))
        self.label_title_11.setText(_translate("MainWindow", "Install adaptor"))
        self.btnNext_scanCT_4.setText(_translate("MainWindow", "Confirm"))
