# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgFootPedal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgFootPedal(object):
    def setupUi(self, DlgFootPedal):
        DlgFootPedal.setObjectName("DlgFootPedal")
        DlgFootPedal.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgFootPedal.resize(847, 918)
        DlgFootPedal.setStyleSheet("QDialog{\n"
"background-color: rgb(77, 140, 187);\n"
"border-image:url(image/aitherbot_background_s50.png);\n"
"border-top:80;\n"
"border-left:900;\n"
"margin-left:10px;\n"
"margin-top:10px;\n"
"}\n"
"\n"
"QWidget{\n"
"font: 24pt \"Arial\";\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(155, 155, 155, 255), stop:0.2 rgba(239, 239, 239, 255), stop:0.5 rgba(239, 239, 239, 255), stop:0.75 rgba(200, 200, 200, 255),  stop:1 rgba(155, 155, 155, 255));\n"
"}\n"
"\n"
"#lblDescription{\n"
"    color:rgb(255, 255, 255);\n"
"    font: 24pt \"Arial\";\n"
"}")
        DlgFootPedal.setModal(True)
        self.gridLayout_2 = QtWidgets.QGridLayout(DlgFootPedal)
        self.gridLayout_2.setContentsMargins(-1, 80, -1, -1)
        self.gridLayout_2.setVerticalSpacing(7)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblDescription = QtWidgets.QLabel(DlgFootPedal)
        self.lblDescription.setText("")
        self.lblDescription.setObjectName("lblDescription")
        self.gridLayout_2.addWidget(self.lblDescription, 1, 0, 1, 1)
        self.lblContent = QtWidgets.QLabel(DlgFootPedal)
        self.lblContent.setAlignment(QtCore.Qt.AlignCenter)
        self.lblContent.setObjectName("lblContent")
        self.gridLayout_2.addWidget(self.lblContent, 2, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnConfirm = QtWidgets.QPushButton(DlgFootPedal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.btnConfirm.sizePolicy().hasHeightForWidth())
        self.btnConfirm.setSizePolicy(sizePolicy)
        self.btnConfirm.setMinimumSize(QtCore.QSize(300, 150))
        self.btnConfirm.setObjectName("btnConfirm")
        self.gridLayout.addWidget(self.btnConfirm, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 3, 0, 1, 1)
        self.wdgPicture = QtWidgets.QStackedWidget(DlgFootPedal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgPicture.sizePolicy().hasHeightForWidth())
        self.wdgPicture.setSizePolicy(sizePolicy)
        self.wdgPicture.setMinimumSize(QtCore.QSize(825, 563))
        self.wdgPicture.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.wdgPicture.setStyleSheet("background-color: rgb(77, 140, 187);")
        self.wdgPicture.setObjectName("wdgPicture")
        self.pgPedal = QtWidgets.QWidget()
        self.pgPedal.setStyleSheet("image:url(image/foot_pedal_and_drag.png)")
        self.pgPedal.setObjectName("pgPedal")
        self.wdgPicture.addWidget(self.pgPedal)
        self.pgPedalPress = QtWidgets.QWidget()
        self.pgPedalPress.setStyleSheet("image:url(image/foot_pedal_press.png)")
        self.pgPedalPress.setObjectName("pgPedalPress")
        self.wdgPicture.addWidget(self.pgPedalPress)
        self.pgSupportArm = QtWidgets.QWidget()
        self.pgSupportArm.setStyleSheet("color:#ffee88")
        self.pgSupportArm.setObjectName("pgSupportArm")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.pgSupportArm)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.wdgAxis1 = QtWidgets.QWidget(self.pgSupportArm)
        self.wdgAxis1.setStyleSheet("background-color: rgb(93, 171, 227);")
        self.wdgAxis1.setObjectName("wdgAxis1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.wdgAxis1)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lblAxis1 = QtWidgets.QLabel(self.wdgAxis1)
        self.lblAxis1.setStyleSheet("color:#ff00aa")
        self.lblAxis1.setObjectName("lblAxis1")
        self.gridLayout_3.addWidget(self.lblAxis1, 0, 0, 1, 1)
        self.wdgIndicatorAxis1 = QtWidgets.QWidget(self.wdgAxis1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgIndicatorAxis1.sizePolicy().hasHeightForWidth())
        self.wdgIndicatorAxis1.setSizePolicy(sizePolicy)
        self.wdgIndicatorAxis1.setMinimumSize(QtCore.QSize(0, 60))
        self.wdgIndicatorAxis1.setMaximumSize(QtCore.QSize(16777215, 60))
        self.wdgIndicatorAxis1.setObjectName("wdgIndicatorAxis1")
        self.gridLayout_3.addWidget(self.wdgIndicatorAxis1, 0, 1, 1, 1)
        self.lblHintAxis1 = QtWidgets.QLabel(self.wdgAxis1)
        self.lblHintAxis1.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblHintAxis1.setStyleSheet("color:rgb(255, 0, 0)")
        self.lblHintAxis1.setText("")
        self.lblHintAxis1.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblHintAxis1.setObjectName("lblHintAxis1")
        self.gridLayout_3.addWidget(self.lblHintAxis1, 1, 1, 1, 1)
        self.gridLayout_3.setColumnStretch(1, 1)
        self.gridLayout_5.addWidget(self.wdgAxis1, 0, 0, 1, 1)
        self.wdgAxis2 = QtWidgets.QWidget(self.pgSupportArm)
        self.wdgAxis2.setStyleSheet("background-color: rgb(93, 171, 227);")
        self.wdgAxis2.setObjectName("wdgAxis2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wdgAxis2)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lblAxis2 = QtWidgets.QLabel(self.wdgAxis2)
        self.lblAxis2.setStyleSheet("color:#00ff90")
        self.lblAxis2.setObjectName("lblAxis2")
        self.gridLayout_4.addWidget(self.lblAxis2, 0, 0, 1, 1)
        self.wdgIndicatorAxis2 = QtWidgets.QWidget(self.wdgAxis2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgIndicatorAxis2.sizePolicy().hasHeightForWidth())
        self.wdgIndicatorAxis2.setSizePolicy(sizePolicy)
        self.wdgIndicatorAxis2.setMinimumSize(QtCore.QSize(0, 60))
        self.wdgIndicatorAxis2.setMaximumSize(QtCore.QSize(16777215, 60))
        self.wdgIndicatorAxis2.setObjectName("wdgIndicatorAxis2")
        self.gridLayout_4.addWidget(self.wdgIndicatorAxis2, 0, 1, 1, 1)
        self.lblHintAxis2 = QtWidgets.QLabel(self.wdgAxis2)
        self.lblHintAxis2.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lblHintAxis2.setStyleSheet("color:rgb(255, 0, 0)")
        self.lblHintAxis2.setText("")
        self.lblHintAxis2.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignTop)
        self.lblHintAxis2.setObjectName("lblHintAxis2")
        self.gridLayout_4.addWidget(self.lblHintAxis2, 1, 1, 1, 1)
        self.gridLayout_4.setColumnStretch(1, 1)
        self.gridLayout_5.addWidget(self.wdgAxis2, 1, 0, 1, 1)
        self.wdgPicture.addWidget(self.pgSupportArm)
        self.gridLayout_2.addWidget(self.wdgPicture, 0, 0, 1, 1)
        self.gridLayout_2.setRowStretch(0, 1)

        self.retranslateUi(DlgFootPedal)
        QtCore.QMetaObject.connectSlotsByName(DlgFootPedal)

    def retranslateUi(self, DlgFootPedal):
        _translate = QtCore.QCoreApplication.translate
        DlgFootPedal.setWindowTitle(_translate("DlgFootPedal", "Dialog"))
        self.lblContent.setText(_translate("DlgFootPedal", "...Please press foot pedal..."))
        self.btnConfirm.setText(_translate("DlgFootPedal", "Position Confirm"))
        self.lblAxis1.setText(_translate("DlgFootPedal", "Axis 1"))
        self.lblAxis2.setText(_translate("DlgFootPedal", "Axis 2"))
