# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot_V2.1\FunctionLib_UI\dlgInstallAdaptor.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgInstallAdaptor(object):
    def setupUi(self, dlgInstallAdaptor):
        dlgInstallAdaptor.setObjectName("dlgInstallAdaptor")
        dlgInstallAdaptor.setWindowModality(QtCore.Qt.NonModal)
        dlgInstallAdaptor.resize(1229, 711)
        dlgInstallAdaptor.setStyleSheet("background-color: #4D8CBB;")
        self.gridLayout = QtWidgets.QGridLayout(dlgInstallAdaptor)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgMedia = QtWidgets.QWidget(dlgInstallAdaptor)
        self.wdgMedia.setMinimumSize(QtCore.QSize(800, 600))
        self.wdgMedia.setMaximumSize(QtCore.QSize(800, 600))
        self.wdgMedia.setStyleSheet("image:url(image/foot_pedal.png)")
        self.wdgMedia.setObjectName("wdgMedia")
        self.gridLayout.addWidget(self.wdgMedia, 0, 0, 1, 1)
        self.label = QtWidgets.QLabel(dlgInstallAdaptor)
        self.label.setMinimumSize(QtCore.QSize(400, 0))
        self.label.setStyleSheet("font: 24pt \"Arial\";\n"
"color: rgb(255, 255, 208);")
        self.label.setWordWrap(True)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 1, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnConfirm = QtWidgets.QPushButton(dlgInstallAdaptor)
        self.btnConfirm.setMinimumSize(QtCore.QSize(200, 80))
        self.btnConfirm.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnConfirm.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnConfirm.setObjectName("btnConfirm")
        self.horizontalLayout.addWidget(self.btnConfirm)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 2)

        self.retranslateUi(dlgInstallAdaptor)
        QtCore.QMetaObject.connectSlotsByName(dlgInstallAdaptor)

    def retranslateUi(self, dlgInstallAdaptor):
        _translate = QtCore.QCoreApplication.translate
        dlgInstallAdaptor.setWindowTitle(_translate("dlgInstallAdaptor", "Dialog"))
        self.label.setText(_translate("dlgInstallAdaptor", "<html><head/><body><p><span style=\" font-size:24pt; color:#ff0000;\">Remove locator and install holder</span><span style=\" font-size:24pt;\"> at the end-effector of AitherBot.</span></p></body></html>"))
        self.btnConfirm.setText(_translate("dlgInstallAdaptor", "OK"))
