# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgFootPedal.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgFootPedal(object):
    def setupUi(self, DlgFootPedal):
        DlgFootPedal.setObjectName("DlgFootPedal")
        DlgFootPedal.setWindowModality(QtCore.Qt.ApplicationModal)
        DlgFootPedal.resize(847, 736)
        DlgFootPedal.setStyleSheet("QDialog{\n"
"background-color: rgb(77, 140, 187);\n"
"border-image:url(image/aitherbot_background_s50.png);\n"
"border-top:80;\n"
"border-left:900;\n"
"margin-left:10px;\n"
"margin-top:10px;\n"
"}\n"
"\n"
"QWidget{\n"
"font: 36pt \"Arial\";\n"
"color: rgb(255, 255, 0);\n"
"}")
        DlgFootPedal.setModal(True)
        self.gridLayout = QtWidgets.QGridLayout(DlgFootPedal)
        self.gridLayout.setContentsMargins(-1, 80, -1, -1)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgPicture = QtWidgets.QWidget(DlgFootPedal)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgPicture.sizePolicy().hasHeightForWidth())
        self.wdgPicture.setSizePolicy(sizePolicy)
        self.wdgPicture.setMinimumSize(QtCore.QSize(825, 563))
        self.wdgPicture.setStyleSheet("image:url(image/foot_pedal.png)")
        self.wdgPicture.setObjectName("wdgPicture")
        self.gridLayout.addWidget(self.wdgPicture, 0, 0, 1, 1)
        self.lblContent = QtWidgets.QLabel(DlgFootPedal)
        self.lblContent.setAlignment(QtCore.Qt.AlignCenter)
        self.lblContent.setObjectName("lblContent")
        self.gridLayout.addWidget(self.lblContent, 1, 0, 1, 1)
        self.gridLayout.setRowStretch(0, 1)

        self.retranslateUi(DlgFootPedal)
        QtCore.QMetaObject.connectSlotsByName(DlgFootPedal)

    def retranslateUi(self, DlgFootPedal):
        _translate = QtCore.QCoreApplication.translate
        DlgFootPedal.setWindowTitle(_translate("DlgFootPedal", "Dialog"))
        self.lblContent.setText(_translate("DlgFootPedal", "...Please press foot pedal..."))
