# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgProcessing.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgProcessing(object):
    def setupUi(self, DlgProcessing):
        DlgProcessing.setObjectName("DlgProcessing")
        DlgProcessing.resize(984, 388)
        self.gridLayout_2 = QtWidgets.QGridLayout(DlgProcessing)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.wdgMain = QtWidgets.QWidget(DlgProcessing)
        self.wdgMain.setStyleSheet("#wdgMain{\n"
"    border-radius:20px;\n"
"}\n"
"\n"
"QWidget{\n"
"    background-color:rgba(93, 161, 209, 180)\n"
"}\n"
"\n"
"QLabel{\n"
"    background-color:none;\n"
"    font: 36pt \"Arial\";\n"
"    color:rgb(255, 255, 255);\n"
"}\n"
"\n"
"#lblContent{\n"
"    font: 12pt \"Arial\";\n"
"}")
        self.wdgMain.setObjectName("wdgMain")
        self.gridLayout = QtWidgets.QGridLayout(self.wdgMain)
        self.gridLayout.setObjectName("gridLayout")
        spacerItem = QtWidgets.QSpacerItem(20, 101, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 0, 0, 1, 1)
        self.pgbLoadDIcom = QtWidgets.QProgressBar(self.wdgMain)
        self.pgbLoadDIcom.setProperty("value", 0)
        self.pgbLoadDIcom.setObjectName("pgbLoadDIcom")
        self.gridLayout.addWidget(self.pgbLoadDIcom, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 4, 0, 1, 1)
        self.label_Processing = QtWidgets.QLabel(self.wdgMain)
        self.label_Processing.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setFamily("Arial")
        font.setPointSize(36)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_Processing.setFont(font)
        self.label_Processing.setScaledContents(True)
        self.label_Processing.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Processing.setObjectName("label_Processing")
        self.gridLayout.addWidget(self.label_Processing, 1, 0, 1, 1)
        self.lblContent = QtWidgets.QLabel(self.wdgMain)
        self.lblContent.setText("")
        self.lblContent.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.lblContent.setObjectName("lblContent")
        self.gridLayout.addWidget(self.lblContent, 2, 0, 1, 1)
        self.gridLayout_2.addWidget(self.wdgMain, 0, 0, 1, 1)

        self.retranslateUi(DlgProcessing)
        QtCore.QMetaObject.connectSlotsByName(DlgProcessing)

    def retranslateUi(self, DlgProcessing):
        _translate = QtCore.QCoreApplication.translate
        DlgProcessing.setWindowTitle(_translate("DlgProcessing", "Dialog"))
        self.label_Processing.setText(_translate("DlgProcessing", "Dicom Image importing..."))
