# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgExportLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgExportLog(object):
    def setupUi(self, dlgExportLog):
        dlgExportLog.setObjectName("dlgExportLog")
        dlgExportLog.resize(723, 617)
        dlgExportLog.setStyleSheet("QPushButton{\n"
"    font: 48px \"Arial\";\n"
"    color: qradialgradient(spread:pad, cx:0.5, cy:1.7, radius:1.7, fx:0.5, fy:1.7, stop:0 rgba(170, 255, 255, 255), stop:0.7 rgba(170, 255, 255, 255), stop:0.71 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:1.5, radius:1, fx:0.5, fy:1, stop:0 rgba(0, 0, 255, 255), stop:0.3 rgba(0, 40, 255, 255), stop:0.7 rgba(40, 85, 255, 255), stop:1 rgba(90, 170, 255, 255));\n"
"    border-radius:10px;\n"
"    border-top:1px solid #ddd;\n"
"    border-left:1px solid #ddd;\n"
"    border-right:2px solid #666;\n"
"    border-bottom:2px solid #666;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-top:2px solid #666;\n"
"    border-left:2px solid #666;\n"
"    border-right:1px solid #ddd;\n"
"    border-bottom:1px solid #ddd;\n"
"}\n"
"\n"
"QCalendarWidget QPushButton{\n"
"    font: 24px \"Arial\";\n"
"    color:rgba(170, 255, 255, 255);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(dlgExportLog)
        self.gridLayout.setObjectName("gridLayout")
        self.lblFrom = QtWidgets.QLabel(dlgExportLog)
        self.lblFrom.setObjectName("lblFrom")
        self.gridLayout.addWidget(self.lblFrom, 0, 0, 1, 1)
        self.lblTo = QtWidgets.QLabel(dlgExportLog)
        self.lblTo.setObjectName("lblTo")
        self.gridLayout.addWidget(self.lblTo, 0, 2, 1, 1)
        self.dateEdit = QtWidgets.QDateTimeEdit(dlgExportLog)
        self.dateEdit.setMinimumDateTime(QtCore.QDateTime(QtCore.QDate(2024, 5, 20), QtCore.QTime(0, 0, 0)))
        self.dateEdit.setCalendarPopup(False)
        self.dateEdit.setObjectName("dateEdit")
        self.gridLayout.addWidget(self.dateEdit, 1, 0, 1, 2)
        self.calendarFrom = QCustomCalendarWidget(dlgExportLog)
        self.calendarFrom.setObjectName("calendarFrom")
        self.gridLayout.addWidget(self.calendarFrom, 2, 0, 1, 2)
        self.btnExport = QtWidgets.QPushButton(dlgExportLog)
        self.btnExport.setMinimumSize(QtCore.QSize(200, 80))
        self.btnExport.setStyleSheet("")
        self.btnExport.setObjectName("btnExport")
        self.gridLayout.addWidget(self.btnExport, 3, 1, 1, 2)

        self.retranslateUi(dlgExportLog)
        QtCore.QMetaObject.connectSlotsByName(dlgExportLog)

    def retranslateUi(self, dlgExportLog):
        _translate = QtCore.QCoreApplication.translate
        dlgExportLog.setWindowTitle(_translate("dlgExportLog", "Export Log"))
        self.lblFrom.setText(_translate("dlgExportLog", "From"))
        self.lblTo.setText(_translate("dlgExportLog", "To"))
        self.btnExport.setText(_translate("dlgExportLog", "Export"))
from FunctionLib_UI.WidgetButton import QCustomCalendarWidget
