# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgExportLog.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgExportLog(object):
    def setupUi(self, dlgExportLog):
        dlgExportLog.setObjectName("dlgExportLog")
        dlgExportLog.resize(723, 617)
        dlgExportLog.setStyleSheet("QPushButton{\n"
"    font: 48px \"Arial\";\n"
"    color: qradialgradient(spread:pad, cx:0.5, cy:1.7, radius:1.7, fx:0.5, fy:1.7, stop:0 rgba(170, 255, 255, 255), stop:0.7 rgba(170, 255, 255, 255), stop:0.71 rgba(0, 0, 255, 255), stop:1 rgba(0, 0, 255, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:1.5, radius:1, fx:0.5, fy:1, stop:0 rgba(0, 0, 255, 255), stop:0.3 rgba(0, 40, 255, 255), stop:0.7 rgba(40, 85, 255, 255), stop:1 rgba(90, 170, 255, 255));\n"
"    border-radius:10px;\n"
"    border-top:1px solid #ddd;\n"
"    border-left:1px solid #ddd;\n"
"    border-right:2px solid #666;\n"
"    border-bottom:2px solid #666;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"    border-top:2px solid #666;\n"
"    border-left:2px solid #666;\n"
"    border-right:1px solid #ddd;\n"
"    border-bottom:1px solid #ddd;\n"
"}\n"
"\n"
"QPushButton:disabled{\n"
"    color: qradialgradient(spread:pad, cx:0.5, cy:1.7, radius:1.7, fx:0.5, fy:1.7, stop:0 rgba(255, 255, 255, 255), stop:0.7 rgba(255, 255, 255, 255), stop:0.71 rgba(100, 100, 100, 255), stop:1 rgba(100, 100, 100, 255));\n"
"    background-color: qradialgradient(spread:pad, cx:0.5, cy:1.5, radius:1, fx:0.5, fy:1, stop:0 rgba(40, 40, 40, 255), stop:0.3 rgba(40, 40, 40, 255), stop:0.7 rgba(100, 100, 100, 255), stop:1 rgba(200, 200, 200, 255));\n"
"}\n"
"\n"
"QCalendarWidget QPushButton{\n"
"    font: 24px \"Arial\";\n"
"    color:rgba(170, 255, 255, 255);\n"
"}")
        self.gridLayout = QtWidgets.QGridLayout(dlgExportLog)
        self.gridLayout.setObjectName("gridLayout")
        self.btnDateFrom = QtWidgets.QPushButton(dlgExportLog)
        self.btnDateFrom.setMinimumSize(QtCore.QSize(0, 80))
        self.btnDateFrom.setStyleSheet("font: 36px \"Arial\";")
        self.btnDateFrom.setObjectName("btnDateFrom")
        self.gridLayout.addWidget(self.btnDateFrom, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnExport = QtWidgets.QPushButton(dlgExportLog)
        self.btnExport.setEnabled(False)
        self.btnExport.setMinimumSize(QtCore.QSize(200, 80))
        self.btnExport.setStyleSheet("")
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout.addWidget(self.btnExport)
        self.gridLayout.addLayout(self.horizontalLayout, 2, 0, 1, 2)
        self.btnDateTo = QtWidgets.QPushButton(dlgExportLog)
        self.btnDateTo.setMinimumSize(QtCore.QSize(0, 80))
        self.btnDateTo.setStyleSheet("font: 36px \"Arial\";")
        self.btnDateTo.setObjectName("btnDateTo")
        self.gridLayout.addWidget(self.btnDateTo, 0, 1, 1, 1)
        self.calendarTo = QCustomCalendarWidget(dlgExportLog)
        self.calendarTo.setObjectName("calendarTo")
        self.gridLayout.addWidget(self.calendarTo, 1, 1, 1, 1)
        self.calendarFrom = QCustomCalendarWidget(dlgExportLog)
        self.calendarFrom.setObjectName("calendarFrom")
        self.gridLayout.addWidget(self.calendarFrom, 1, 0, 1, 1)
        self.pbrProgress = QtWidgets.QProgressBar(dlgExportLog)
        self.pbrProgress.setProperty("value", 0)
        self.pbrProgress.setObjectName("pbrProgress")
        self.gridLayout.addWidget(self.pbrProgress, 3, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)

        self.retranslateUi(dlgExportLog)
        QtCore.QMetaObject.connectSlotsByName(dlgExportLog)

    def retranslateUi(self, dlgExportLog):
        _translate = QtCore.QCoreApplication.translate
        dlgExportLog.setWindowTitle(_translate("dlgExportLog", "Export Log"))
        self.btnDateFrom.setText(_translate("dlgExportLog", "Select From Date"))
        self.btnExport.setText(_translate("dlgExportLog", "Export"))
        self.btnDateTo.setText(_translate("dlgExportLog", "Select To Date"))
from FunctionLib_UI.WidgetButton import QCustomCalendarWidget
