# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\Aitherbot-Project-V1.9.5\FunctionLib_UI\DlgRobotMoving.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgRobotMoving(object):
    def setupUi(self, DlgRobotMoving):
        DlgRobotMoving.setObjectName("DlgRobotMoving")
        DlgRobotMoving.resize(524, 389)
        self.gridLayout = QtWidgets.QGridLayout(DlgRobotMoving)
        self.gridLayout.setObjectName("gridLayout")
        self.btnStop = QtWidgets.QPushButton(DlgRobotMoving)
        self.btnStop.setMinimumSize(QtCore.QSize(256, 256))
        self.btnStop.setMaximumSize(QtCore.QSize(256, 256))
        self.btnStop.setStyleSheet("QPushButton{\n"
"image:url(C:/Leon/image/stop-sign.png);\n"
"background-color: rgb(93, 161, 209);\n"
"border-left:1px solid #ccc;\n"
"border-top:1px solid #ccc;\n"
"border-right:2px solid #555;\n"
"border-bottom:2px solid #555;\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"/*margin-top:2px;\n"
"margin-left:1px;*/\n"
"border-left:2px solid #555;\n"
"border-top:2px solid #555;\n"
"border-right:1px solid #ccc;\n"
"border-bottom:1px solid #ccc;\n"
"}")
        self.btnStop.setText("")
        self.btnStop.setObjectName("btnStop")
        self.gridLayout.addWidget(self.btnStop, 0, 0, 1, 1)
        self.lblRobotMoving = QtWidgets.QLabel(DlgRobotMoving)
        self.lblRobotMoving.setStyleSheet("font: 24pt \"Arial\";\n"
"color:rgb(255, 0, 0);")
        self.lblRobotMoving.setObjectName("lblRobotMoving")
        self.gridLayout.addWidget(self.lblRobotMoving, 1, 0, 1, 1)

        self.retranslateUi(DlgRobotMoving)
        QtCore.QMetaObject.connectSlotsByName(DlgRobotMoving)

    def retranslateUi(self, DlgRobotMoving):
        _translate = QtCore.QCoreApplication.translate
        DlgRobotMoving.setWindowTitle(_translate("DlgRobotMoving", "Dialog"))
        self.lblRobotMoving.setText(_translate("DlgRobotMoving", "Robot Moving..."))
