# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgBreathingDetector.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgBreathingDetector(object):
    def setupUi(self, DlgBreathingDetector):
        DlgBreathingDetector.setObjectName("DlgBreathingDetector")
        DlgBreathingDetector.resize(1100, 826)
        self.gridLayout = QtWidgets.QGridLayout(DlgBreathingDetector)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgDetector = QtWidgets.QWidget(DlgBreathingDetector)
        self.wdgDetector.setObjectName("wdgDetector")
        self.gridLayout.addWidget(self.wdgDetector, 0, 0, 1, 1)

        self.retranslateUi(DlgBreathingDetector)
        QtCore.QMetaObject.connectSlotsByName(DlgBreathingDetector)

    def retranslateUi(self, DlgBreathingDetector):
        _translate = QtCore.QCoreApplication.translate
        DlgBreathingDetector.setWindowTitle(_translate("DlgBreathingDetector", "Dialog"))
