# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot_V2.1\FunctionLib_UI\dlgHint.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(873, 615)
        self.gridLayout = QtWidgets.QGridLayout(Form)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgHintVideo = QtWidgets.QWidget(Form)
        self.wdgHintVideo.setObjectName("wdgHintVideo")
        self.gridLayout.addWidget(self.wdgHintVideo, 0, 0, 1, 1)
        self.btnOK = QtWidgets.QPushButton(Form)
        self.btnOK.setMinimumSize(QtCore.QSize(0, 50))
        self.btnOK.setObjectName("btnOK")
        self.gridLayout.addWidget(self.btnOK, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(Form)
        self.label.setMaximumSize(QtCore.QSize(16777215, 80))
        self.label.setStyleSheet("font: 24pt \"Arial\";")
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Hint"))
        self.btnOK.setText(_translate("Form", "OK"))
        self.label.setText(_translate("Form", "<html><head/><body><p><span style=\" font-size:24pt;\">Switch </span><span style=\" font-size:24pt; color:#ff0000;\">Inhale / Exhale</span><span style=\" font-size:24pt;\"> button to select correspond image</span></p></body></html>"))
