# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\DlgLogViewer.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgLogViewer(object):
    def setupUi(self, DlgLogViewer):
        DlgLogViewer.setObjectName("DlgLogViewer")
        DlgLogViewer.resize(1600, 637)
        DlgLogViewer.setMinimumSize(QtCore.QSize(1600, 0))
        DlgLogViewer.setStyleSheet("QWidget{\n"
"    font: 18px \"Arial\";\n"
"    color:rgb(197, 255, 246);\n"
"}\n"
"\n"
"QDialog{\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 1, y2: 1,\n"
"                                 stop: 0 #848484, stop: 0.4 #a4a4a4,\n"
"                                 stop: 0.5 #a4a4a4, stop: 1.0 #848484);\n"
"}\n"
"\n"
"QPushButton{\n"
"    color: rgb(197, 255, 246);\n"
"    /*background-color: rgb(0, 0, 127);*/\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                 stop: 0 rgb(0, 0, 127), stop: 0.2 rgb(112, 118, 139),\n"
"                                 stop: 0.4 rgb(155, 155, 155), stop: 1.0  rgb(0, 0, 127));\n"
"    border-radius:3px;\n"
"    border-top:1px solid #ddd;\n"
"    border-left:1px solid #ddd;\n"
"    border-bottom:2px solid #444;\n"
"    border-right:2px solid #444;\n"
"}\n"
"\n"
"QPushButton:checked{\n"
"    color: rgb(255, 255, 0);\n"
"    background-color:rgb(85, 0, 255);\n"
"    border-bottom:1px solid #ddd;\n"
"    border-right:1px solid #ddd;\n"
"    border-top:2px solid #444;\n"
"    border-left:2px solid #444;\n"
"}\n"
"\n"
"QHeaderView:section{\n"
"    background-color: qlineargradient(x1: 0, y1: 1, x2: 1, y2: 0,\n"
"                                 stop: 0 rgb(0, 0, 127), \n"
"                                 /*stop: 0.2 rgb(0, 0, 127),*/\n"
"                                 stop: 1 rgb(112, 118, 139));\n"
"    color:rgb(197, 255, 246);\n"
"    font: 16px \"Arial\";\n"
"}\n"
"\n"
"QTreeWidget{\n"
"    outline:0px;\n"
"    background-color:#090909;\n"
"    color:#F4EDFF;\n"
"}\n"
"\n"
"QTreeWidget::item, QTreeWidget::branch{\n"
"    margin-top:1px;\n"
"    margin-bottom:1px;\n"
"    background-color:#353534;\n"
"    color:#F4EDFF;\n"
"}\n"
"\n"
"QTreeWidget::item:selected, QTreeWidget::branch:selected{\n"
"    background-color:rgb(88, 56, 100);\n"
"}\n"
"\n"
"QTreeWidget::branch:closed:has-children{\n"
"    image:url(image/arrow-right.png)\n"
"}\n"
"\n"
"QTreeWidget::branch:open:has-children{\n"
"    image:url(image/arrow-down.png)\n"
"}\n"
"\n"
"QLineEdit{\n"
"    background-color:#090909;\n"
"}\n"
"")
        self.gridLayout = QtWidgets.QGridLayout(DlgLogViewer)
        self.gridLayout.setSpacing(7)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(DlgLogViewer)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.ledSearch = QtWidgets.QLineEdit(DlgLogViewer)
        self.ledSearch.setObjectName("ledSearch")
        self.horizontalLayout_2.addWidget(self.ledSearch)
        self.label = QtWidgets.QLabel(DlgLogViewer)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.btnAll = QtWidgets.QPushButton(DlgLogViewer)
        self.btnAll.setMinimumSize(QtCore.QSize(120, 30))
        self.btnAll.setCheckable(True)
        self.btnAll.setChecked(True)
        self.btnAll.setObjectName("btnAll")
        self.horizontalLayout.addWidget(self.btnAll)
        self.btnDebug = QtWidgets.QPushButton(DlgLogViewer)
        self.btnDebug.setMinimumSize(QtCore.QSize(120, 30))
        self.btnDebug.setCheckable(True)
        self.btnDebug.setObjectName("btnDebug")
        self.horizontalLayout.addWidget(self.btnDebug)
        self.btnInfo = QtWidgets.QPushButton(DlgLogViewer)
        self.btnInfo.setMinimumSize(QtCore.QSize(120, 30))
        self.btnInfo.setCheckable(True)
        self.btnInfo.setObjectName("btnInfo")
        self.horizontalLayout.addWidget(self.btnInfo)
        self.btnWarning = QtWidgets.QPushButton(DlgLogViewer)
        self.btnWarning.setMinimumSize(QtCore.QSize(120, 30))
        self.btnWarning.setCheckable(True)
        self.btnWarning.setObjectName("btnWarning")
        self.horizontalLayout.addWidget(self.btnWarning)
        self.btnError = QtWidgets.QPushButton(DlgLogViewer)
        self.btnError.setMinimumSize(QtCore.QSize(120, 30))
        self.btnError.setCheckable(True)
        self.btnError.setObjectName("btnError")
        self.horizontalLayout.addWidget(self.btnError)
        self.btnCritical = QtWidgets.QPushButton(DlgLogViewer)
        self.btnCritical.setMinimumSize(QtCore.QSize(120, 30))
        self.btnCritical.setCheckable(True)
        self.btnCritical.setObjectName("btnCritical")
        self.horizontalLayout.addWidget(self.btnCritical)
        self.horizontalLayout_2.addLayout(self.horizontalLayout)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_2, 0, 0, 1, 2)
        self.treeLogList = QtWidgets.QTreeWidget(DlgLogViewer)
        self.treeLogList.setMinimumSize(QtCore.QSize(300, 0))
        self.treeLogList.setStyleSheet("")
        self.treeLogList.setAutoExpandDelay(-1)
        self.treeLogList.setAnimated(True)
        self.treeLogList.setExpandsOnDoubleClick(True)
        self.treeLogList.setObjectName("treeLogList")
        self.gridLayout.addWidget(self.treeLogList, 1, 0, 1, 1)
        self.treeLogView = QtWidgets.QTreeWidget(DlgLogViewer)
        self.treeLogView.setStyleSheet("")
        self.treeLogView.setAlternatingRowColors(False)
        self.treeLogView.setObjectName("treeLogView")
        self.gridLayout.addWidget(self.treeLogView, 1, 1, 1, 1)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.btnExport = NaviButton(DlgLogViewer)
        self.btnExport.setMinimumSize(QtCore.QSize(0, 80))
        self.btnExport.setMaximumSize(QtCore.QSize(300, 16777215))
        self.btnExport.setObjectName("btnExport")
        self.horizontalLayout_3.addWidget(self.btnExport)
        self.gridLayout.addLayout(self.horizontalLayout_3, 2, 0, 1, 2)
        self.gridLayout.setColumnStretch(0, 2)
        self.gridLayout.setColumnStretch(1, 5)

        self.retranslateUi(DlgLogViewer)
        QtCore.QMetaObject.connectSlotsByName(DlgLogViewer)

    def retranslateUi(self, DlgLogViewer):
        _translate = QtCore.QCoreApplication.translate
        DlgLogViewer.setWindowTitle(_translate("DlgLogViewer", "Dialog"))
        self.label_2.setText(_translate("DlgLogViewer", "search"))
        self.label.setText(_translate("DlgLogViewer", "Level"))
        self.btnAll.setText(_translate("DlgLogViewer", "All"))
        self.btnDebug.setText(_translate("DlgLogViewer", "Debug"))
        self.btnInfo.setText(_translate("DlgLogViewer", "Info"))
        self.btnWarning.setText(_translate("DlgLogViewer", "Warning"))
        self.btnError.setText(_translate("DlgLogViewer", "Error"))
        self.btnCritical.setText(_translate("DlgLogViewer", "Critical"))
        self.treeLogList.headerItem().setText(0, _translate("DlgLogViewer", "Date"))
        self.treeLogList.headerItem().setText(1, _translate("DlgLogViewer", "Time"))
        self.treeLogView.headerItem().setText(0, _translate("DlgLogViewer", "ID"))
        self.treeLogView.headerItem().setText(1, _translate("DlgLogViewer", "Level"))
        self.treeLogView.headerItem().setText(2, _translate("DlgLogViewer", "Model"))
        self.treeLogView.headerItem().setText(3, _translate("DlgLogViewer", "Message"))
        self.btnExport.setText(_translate("DlgLogViewer", "Export"))
from FunctionLib_UI.WidgetButton import NaviButton
