# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\Aitherbot-Project-V1.9.5\FunctionLib_UI\homing.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_dlgHoming(object):
    def setupUi(self, dlgHoming):
        dlgHoming.setObjectName("dlgHoming")
        dlgHoming.resize(825, 775)
        dlgHoming.setMinimumSize(QtCore.QSize(800, 600))
        dlgHoming.setMaximumSize(QtCore.QSize(16777215, 16777215))
        dlgHoming.setStyleSheet("")
        self.gridLayout = QtWidgets.QGridLayout(dlgHoming)
        self.gridLayout.setObjectName("gridLayout")
        self.wdgHoming = QtWidgets.QWidget(dlgHoming)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgHoming.sizePolicy().hasHeightForWidth())
        self.wdgHoming.setSizePolicy(sizePolicy)
        self.wdgHoming.setMinimumSize(QtCore.QSize(800, 600))
        self.wdgHoming.setMaximumSize(QtCore.QSize(800, 600))
        self.wdgHoming.setObjectName("wdgHoming")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.wdgHoming)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout.addWidget(self.wdgHoming, 0, 0, 1, 1)
        self.layoutH = QtWidgets.QHBoxLayout()
        self.layoutH.setSpacing(0)
        self.layoutH.setObjectName("layoutH")
        self.btnStartHoming = QtWidgets.QPushButton(dlgHoming)
        self.btnStartHoming.setMinimumSize(QtCore.QSize(240, 140))
        self.btnStartHoming.setMaximumSize(QtCore.QSize(200, 16777215))
        self.btnStartHoming.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.btnStartHoming.setObjectName("btnStartHoming")
        self.layoutH.addWidget(self.btnStartHoming)
        self.gridLayout.addLayout(self.layoutH, 2, 0, 1, 1)
        self.label = QtWidgets.QLabel(dlgHoming)
        self.label.setStyleSheet("font: 24pt \"Arial\";")
        self.label.setTextFormat(QtCore.Qt.MarkdownText)
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 0, 1, 1)

        self.retranslateUi(dlgHoming)
        QtCore.QMetaObject.connectSlotsByName(dlgHoming)

    def retranslateUi(self, dlgHoming):
        _translate = QtCore.QCoreApplication.translate
        dlgHoming.setWindowTitle(_translate("dlgHoming", "Dialog"))
        self.btnStartHoming.setText(_translate("dlgHoming", "Start"))
        self.label.setText(_translate("dlgHoming", "<html><head/><body><p><span style=\" font-size:24pt;\">Press </span><span style=\" font-size:24pt; color:#ff0000;\">Start</span><span style=\" font-size:24pt;\"> will start Robot Homing</span></p><p><span style=\" font-size:24pt;\">Please </span><span style=\" font-size:24pt; color:#ff0000;\">DON\'T CLOSE</span><span style=\" font-size:24pt;\"> to Robot</span></p></body></html>"))
