# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FunctionLib_UI/ui_processing.ui'
#
# Created by: PyQt5 UI code generator 5.15.7
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(846, 579)
        Form.setStyleSheet("#label_Background {\n"
"background-color:rgba(0,0,0,120);\n"
"}")
        self.label_Processing = QtWidgets.QLabel(Form)
        self.label_Processing.setGeometry(QtCore.QRect(300, 220, 211, 121))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.label_Processing.setFont(font)
        self.label_Processing.setScaledContents(True)
        self.label_Processing.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Processing.setObjectName("label_Processing")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Processing.setText(_translate("Form", "loading"))
