# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FunctionLib_UI/ui_processing.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(842, 328)
        Form.setStyleSheet("#label_Background {\n"
"background-color:rgba(0,0,0,120);\n"
"}")
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label_Processing = QtWidgets.QLabel(Form)
        self.label_Processing.setMaximumSize(QtCore.QSize(16777215, 300))
        font = QtGui.QFont()
        font.setPointSize(40)
        self.label_Processing.setFont(font)
        self.label_Processing.setScaledContents(True)
        self.label_Processing.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Processing.setObjectName("label_Processing")
        self.gridLayout.addWidget(self.label_Processing, 1, 0, 1, 1)
        self.pgbLoadDIcom = QtWidgets.QProgressBar(Form)
        self.pgbLoadDIcom.setProperty("value", 0)
        self.pgbLoadDIcom.setObjectName("pgbLoadDIcom")
        self.gridLayout.addWidget(self.pgbLoadDIcom, 2, 0, 1, 1)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem, 3, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout.addItem(spacerItem1, 0, 0, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 0, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_Processing.setText(_translate("Form", "Loading"))
