# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\AitherBot\AitherBot_V3.2\FunctionLib_UI\RobotCalibration.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_DlgRobotCalibration(object):
    def setupUi(self, DlgRobotCalibration):
        DlgRobotCalibration.setObjectName("DlgRobotCalibration")
        DlgRobotCalibration.resize(985, 669)
        DlgRobotCalibration.setStyleSheet("#DlgRobotCalibration{background-color: rgb(0, 0, 0);}\n"
"\n"
"QGroupBox{color:#ffffff}\n"
"\n"
"QLabel{\n"
"    color:#ffffff\n"
"}")
        self.gridLayout_3 = QtWidgets.QGridLayout(DlgRobotCalibration)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.canvasXZ = QtWidgets.QLabel(DlgRobotCalibration)
        self.canvasXZ.setText("")
        self.canvasXZ.setObjectName("canvasXZ")
        self.gridLayout_3.addWidget(self.canvasXZ, 0, 0, 1, 1)
        self.canvasYZ = QtWidgets.QLabel(DlgRobotCalibration)
        self.canvasYZ.setText("")
        self.canvasYZ.setObjectName("canvasYZ")
        self.gridLayout_3.addWidget(self.canvasYZ, 0, 1, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.btnRobotRun = QtWidgets.QPushButton(DlgRobotCalibration)
        self.btnRobotRun.setMinimumSize(QtCore.QSize(0, 80))
        self.btnRobotRun.setObjectName("btnRobotRun")
        self.gridLayout.addWidget(self.btnRobotRun, 0, 2, 1, 1)
        self.btnGetImage = QtWidgets.QPushButton(DlgRobotCalibration)
        self.btnGetImage.setMinimumSize(QtCore.QSize(0, 80))
        self.btnGetImage.setObjectName("btnGetImage")
        self.gridLayout.addWidget(self.btnGetImage, 0, 1, 1, 1)
        self.gbxCoordinate = QtWidgets.QGroupBox(DlgRobotCalibration)
        self.gbxCoordinate.setObjectName("gbxCoordinate")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gbxCoordinate)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.lblZ_2 = QtWidgets.QLabel(self.gbxCoordinate)
        self.lblZ_2.setObjectName("lblZ_2")
        self.gridLayout_2.addWidget(self.lblZ_2, 1, 4, 1, 1)
        self.ledX2 = QtWidgets.QLineEdit(self.gbxCoordinate)
        self.ledX2.setObjectName("ledX2")
        self.gridLayout_2.addWidget(self.ledX2, 1, 1, 1, 1)
        self.ledY1 = QtWidgets.QLineEdit(self.gbxCoordinate)
        self.ledY1.setObjectName("ledY1")
        self.gridLayout_2.addWidget(self.ledY1, 0, 3, 1, 1)
        self.ledZ2 = QtWidgets.QLineEdit(self.gbxCoordinate)
        self.ledZ2.setObjectName("ledZ2")
        self.gridLayout_2.addWidget(self.ledZ2, 1, 5, 1, 1)
        self.lblX = QtWidgets.QLabel(self.gbxCoordinate)
        self.lblX.setObjectName("lblX")
        self.gridLayout_2.addWidget(self.lblX, 0, 0, 1, 1)
        self.lblX_2 = QtWidgets.QLabel(self.gbxCoordinate)
        self.lblX_2.setObjectName("lblX_2")
        self.gridLayout_2.addWidget(self.lblX_2, 1, 0, 1, 1)
        self.ledZ1 = QtWidgets.QLineEdit(self.gbxCoordinate)
        self.ledZ1.setObjectName("ledZ1")
        self.gridLayout_2.addWidget(self.ledZ1, 0, 5, 1, 1)
        self.ledY2 = QtWidgets.QLineEdit(self.gbxCoordinate)
        self.ledY2.setObjectName("ledY2")
        self.gridLayout_2.addWidget(self.ledY2, 1, 3, 1, 1)
        self.ledX1 = QtWidgets.QLineEdit(self.gbxCoordinate)
        self.ledX1.setObjectName("ledX1")
        self.gridLayout_2.addWidget(self.ledX1, 0, 1, 1, 1)
        self.lblY = QtWidgets.QLabel(self.gbxCoordinate)
        self.lblY.setObjectName("lblY")
        self.gridLayout_2.addWidget(self.lblY, 0, 2, 1, 1)
        self.lblZ = QtWidgets.QLabel(self.gbxCoordinate)
        self.lblZ.setObjectName("lblZ")
        self.gridLayout_2.addWidget(self.lblZ, 0, 4, 1, 1)
        self.lblY_2 = QtWidgets.QLabel(self.gbxCoordinate)
        self.lblY_2.setObjectName("lblY_2")
        self.gridLayout_2.addWidget(self.lblY_2, 1, 2, 1, 1)
        self.gridLayout.addWidget(self.gbxCoordinate, 0, 3, 1, 1)
        self.btnGetPnp = QtWidgets.QPushButton(DlgRobotCalibration)
        self.btnGetPnp.setMinimumSize(QtCore.QSize(0, 80))
        self.btnGetPnp.setObjectName("btnGetPnp")
        self.gridLayout.addWidget(self.btnGetPnp, 0, 0, 1, 1)
        self.gridLayout.setColumnStretch(0, 1)
        self.gridLayout.setColumnStretch(1, 1)
        self.gridLayout_3.addLayout(self.gridLayout, 1, 0, 1, 2)
        self.gridLayout_3.setRowStretch(0, 1)

        self.retranslateUi(DlgRobotCalibration)
        QtCore.QMetaObject.connectSlotsByName(DlgRobotCalibration)

    def retranslateUi(self, DlgRobotCalibration):
        _translate = QtCore.QCoreApplication.translate
        DlgRobotCalibration.setWindowTitle(_translate("DlgRobotCalibration", "Dialog"))
        self.btnRobotRun.setText(_translate("DlgRobotCalibration", "Robot Run"))
        self.btnGetImage.setText(_translate("DlgRobotCalibration", "Get Robot Image"))
        self.gbxCoordinate.setTitle(_translate("DlgRobotCalibration", "Coordinate"))
        self.lblZ_2.setText(_translate("DlgRobotCalibration", "Z2"))
        self.lblX.setText(_translate("DlgRobotCalibration", "X1"))
        self.lblX_2.setText(_translate("DlgRobotCalibration", "X2"))
        self.lblY.setText(_translate("DlgRobotCalibration", "Y1"))
        self.lblZ.setText(_translate("DlgRobotCalibration", "Z1"))
        self.lblY_2.setText(_translate("DlgRobotCalibration", "Y2"))
        self.btnGetPnp.setText(_translate("DlgRobotCalibration", "Get Camera Matrix"))
