# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'FunctionLib_UI/ui_set_point_system.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from vtk.qt.QVTKRenderWindowInteractor import QVTKRenderWindowInteractor

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(858, 711)
        self.Button_OK_and_close = QtWidgets.QPushButton(Form)
        self.Button_OK_and_close.setGeometry(QtCore.QRect(100, 660, 93, 28))
        self.Button_OK_and_close.setObjectName("Button_OK_and_close")
        self.qvtkWidget = QVTKRenderWindowInteractor(Form)
        self.qvtkWidget.setGeometry(QtCore.QRect(20, 20, 821, 621))
        self.qvtkWidget.setObjectName("qvtkWidget")

        self.retranslateUi(Form)
        self.Button_OK_and_close.clicked.connect(Form.okAndClose)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.Button_OK_and_close.setText(_translate("Form", "OK and close"))
