# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'c:\Leon\Aitherbot-Project-V1.9.4\FunctionLib_UI\ui_demo_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1280, 960)
        MainWindow.setMinimumSize(QtCore.QSize(1280, 960))
        MainWindow.setStyleSheet("#MainWindow{background-color: rgb(0, 0, 0);}\n"
"\n"
"#centralwidget{background-color: rgb(0, 0, 0);}")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.stkScene = QtWidgets.QStackedWidget(self.centralwidget)
        self.stkScene.setStyleSheet("#stkScene > QWidget{\n"
"    background-color:#000000;\n"
"}")
        self.stkScene.setObjectName("stkScene")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.gridLayout_8 = QtWidgets.QGridLayout(self.page)
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.wdgModeSelection = QtWidgets.QWidget(self.page)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgModeSelection.sizePolicy().hasHeightForWidth())
        self.wdgModeSelection.setSizePolicy(sizePolicy)
        self.wdgModeSelection.setMinimumSize(QtCore.QSize(1024, 576))
        self.wdgModeSelection.setMaximumSize(QtCore.QSize(1024, 576))
        self.wdgModeSelection.setAutoFillBackground(False)
        self.wdgModeSelection.setStyleSheet("#wdgModeSelection{\n"
"    background-image:url(C:/Leon/image/background.jpg);\n"
"}\n"
"\n"
"QPushButton{\n"
"font: 36pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 0), stop:0.1 rgba(255, 255, 255, 100), stop:0.3 rgba(255, 255, 255, 255), stop:0.6 rgba(255, 255, 255, 230), stop:1 rgba(255, 255, 255, 50));\n"
"border:0px;\n"
"border-radius:40px;\n"
"margin:10px;\n"
"padding:10px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(88, 238, 255, 0), stop:0.1 rgba(88, 238, 255, 100), stop:0.3 rgba(88, 238, 255, 255), stop:0.6 rgba(88, 238, 255, 230), stop:1 rgba(88, 238, 255, 50));\n"
"}")
        self.wdgModeSelection.setObjectName("wdgModeSelection")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.wdgModeSelection)
        self.gridLayout_4.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout_4.setVerticalSpacing(0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem, 5, 3, 1, 1)
        self.widget_4 = QtWidgets.QWidget(self.wdgModeSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setMinimumSize(QtCore.QSize(0, 200))
        self.widget_4.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget_4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget_4.setStyleSheet("QWidget{\n"
"font: 32pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 0), stop:0.1 rgba(255, 255, 255, 100), stop:0.3 rgba(255, 255, 255, 255), stop:0.6 rgba(255, 255, 255, 230), stop:1 rgba(255, 255, 255, 50));\n"
"border:0px;\n"
"border-radius:40px;\n"
"padding:0px;\n"
"margin:10px;\n"
"}\n"
"\n"
"QWidget:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(88, 238, 255, 0), stop:0.1 rgba(88, 238, 255, 100), stop:0.3 rgba(88, 238, 255, 255), stop:0.6 rgba(88, 238, 255, 230), stop:1 rgba(88, 238, 255, 50));\n"
"}\n"
"\n"
"QLabel{\n"
"    margin-top:0px;\n"
"    margin-bottom:0px;\n"
"    padding:0px;\n"
"}")
        self.widget_4.setObjectName("widget_4")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.widget_4)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.label_3 = QtWidgets.QLabel(self.widget_4)
        self.label_3.setStyleSheet("background:none;\n"
"font: 14pt \"Arial\";")
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.gridLayout_6.addWidget(self.label_3, 2, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget_4)
        self.label_4.setStyleSheet("background:none;")
        self.label_4.setObjectName("label_4")
        self.gridLayout_6.addWidget(self.label_4, 1, 0, 1, 1)
        spacerItem1 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem1, 0, 0, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_6.addItem(spacerItem2, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget_4, 5, 2, 1, 1)
        self.label_title_2 = QtWidgets.QLabel(self.wdgModeSelection)
        self.label_title_2.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_2.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_2.setStyleSheet("#label_title_2{\n"
"    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;\n"
"}")
        self.label_title_2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_2.setObjectName("label_title_2")
        self.gridLayout_4.addWidget(self.label_title_2, 1, 0, 1, 4)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_4.addItem(spacerItem3, 5, 0, 1, 1)
        self.widget = QtWidgets.QWidget(self.wdgModeSelection)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Maximum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setMinimumSize(QtCore.QSize(0, 200))
        self.widget.setMaximumSize(QtCore.QSize(16777215, 200))
        self.widget.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.widget.setMouseTracking(False)
        self.widget.setFocusPolicy(QtCore.Qt.ClickFocus)
        self.widget.setStyleSheet("QWidget{\n"
"font: 32pt \"Arial\";\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(255, 255, 255, 0), stop:0.1 rgba(255, 255, 255, 100), stop:0.3 rgba(255, 255, 255, 255), stop:0.6 rgba(255, 255, 255, 230), stop:1 rgba(255, 255, 255, 50));\n"
"border:0px;\n"
"border-radius:40px;\n"
"padding:0px;\n"
"margin:10px;\n"
"}\n"
"\n"
"QWidget:hover{\n"
"    background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(88, 238, 255, 0), stop:0.1 rgba(88, 238, 255, 100), stop:0.3 rgba(88, 238, 255, 255), stop:0.6 rgba(88, 238, 255, 230), stop:1 rgba(88, 238, 255, 50));\n"
"}\n"
"\n"
"\n"
"QLabel{\n"
"    margin-top:0px;\n"
"    margin-bottom:0px;\n"
"    padding:0px;\n"
"}")
        self.widget.setObjectName("widget")
        self.gridLayout_7 = QtWidgets.QGridLayout(self.widget)
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setStyleSheet("background:none;\n"
"font: 14pt \"Arial\";")
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_7.addWidget(self.label_5, 2, 0, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setStyleSheet("background:none;")
        self.label_6.setObjectName("label_6")
        self.gridLayout_7.addWidget(self.label_6, 1, 0, 1, 1)
        spacerItem4 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem4, 0, 0, 1, 1)
        spacerItem5 = QtWidgets.QSpacerItem(10, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_7.addItem(spacerItem5, 3, 0, 1, 1)
        self.gridLayout_4.addWidget(self.widget, 5, 1, 1, 1)
        spacerItem6 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_4.addItem(spacerItem6, 4, 1, 1, 2)
        self.label_subtitle_2 = QtWidgets.QLabel(self.wdgModeSelection)
        self.label_subtitle_2.setStyleSheet("    color:#eeeeee;\n"
"    font: 18pt \"Cascadia Code SemiBold\";\n"
"    margin-right:240px;")
        self.label_subtitle_2.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_subtitle_2.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_subtitle_2.setObjectName("label_subtitle_2")
        self.gridLayout_4.addWidget(self.label_subtitle_2, 2, 0, 1, 4)
        self.gridLayout_8.addWidget(self.wdgModeSelection, 0, 0, 1, 1)
        self.stkScene.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.gridLayout_5 = QtWidgets.QGridLayout(self.page_2)
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.mainWidget = QtWidgets.QWidget(self.page_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.mainWidget.sizePolicy().hasHeightForWidth())
        self.mainWidget.setSizePolicy(sizePolicy)
        self.mainWidget.setMinimumSize(QtCore.QSize(1024, 576))
        self.mainWidget.setMaximumSize(QtCore.QSize(1024, 576))
        self.mainWidget.setAutoFillBackground(False)
        self.mainWidget.setStyleSheet("#mainWidget{\n"
"    background-image:url(C:/Leon/image/background.jpg);\n"
"}")
        self.mainWidget.setObjectName("mainWidget")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.mainWidget)
        self.gridLayout_2.setContentsMargins(-1, 11, -1, -1)
        self.gridLayout_2.setVerticalSpacing(0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_title = QtWidgets.QLabel(self.mainWidget)
        self.label_title.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title.setStyleSheet("#label_title{\n"
"    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;\n"
"}")
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.gridLayout_2.addWidget(self.label_title, 0, 1, 1, 1)
        self.wdgProgress = QtWidgets.QWidget(self.mainWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.wdgProgress.sizePolicy().hasHeightForWidth())
        self.wdgProgress.setSizePolicy(sizePolicy)
        self.wdgProgress.setMinimumSize(QtCore.QSize(600, 96))
        self.wdgProgress.setStyleSheet("#wdgProgress{\n"
"    \n"
"background-color: rgba(120, 120, 120, 180);\n"
"border-radius:10px;\n"
"}\n"
"\n"
"QProgressBar{\n"
"    color:rgb(255, 255, 255);\n"
"    background-color:rgba(255, 255, 255, 100);\n"
"    border:0px;\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"\n"
"\n"
"\n"
"\n"
"QProgressBar::chunk[value=\"100\"]{\n"
"    background-color:rgb(0, 160, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"\n"
"QProgressBar[value=\"100\"]{\n"
"    color: rgb(255, 255, 0);\n"
"    border-radius:5px;\n"
"}\n"
"\n"
"QLabel{\n"
"    font: 9pt \"Arial\";\n"
"    color:#ffffff;\n"
"}\n"
"")
        self.wdgProgress.setObjectName("wdgProgress")
        self.gridLayout = QtWidgets.QGridLayout(self.wdgProgress)
        self.gridLayout.setObjectName("gridLayout")
        self.progressBar = QtWidgets.QProgressBar(self.wdgProgress)
        self.progressBar.setStyleSheet("")
        self.progressBar.setMaximum(100)
        self.progressBar.setProperty("value", 100)
        self.progressBar.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar.setTextVisible(True)
        self.progressBar.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar.setInvertedAppearance(False)
        self.progressBar.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar.setObjectName("progressBar")
        self.gridLayout.addWidget(self.progressBar, 1, 2, 1, 1)
        self.widget_3 = QtWidgets.QWidget(self.wdgProgress)
        self.widget_3.setMinimumSize(QtCore.QSize(32, 32))
        self.widget_3.setMaximumSize(QtCore.QSize(32, 32))
        self.widget_3.setStyleSheet("background:none;\n"
"border-image:url(C:/Leon/image/check.png);\n"
"border:0px;")
        self.widget_3.setObjectName("widget_3")
        self.gridLayout.addWidget(self.widget_3, 1, 0, 1, 1)
        self.label = QtWidgets.QLabel(self.wdgProgress)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 1, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.wdgProgress)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 2, 1, 1, 1)
        self.widget_2 = QtWidgets.QWidget(self.wdgProgress)
        self.widget_2.setMinimumSize(QtCore.QSize(32, 32))
        self.widget_2.setMaximumSize(QtCore.QSize(32, 32))
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.gridLayout.addWidget(self.widget_2, 2, 0, 1, 1)
        self.progressBar_2 = QtWidgets.QProgressBar(self.wdgProgress)
        self.progressBar_2.setStyleSheet("")
        self.progressBar_2.setProperty("value", 95)
        self.progressBar_2.setAlignment(QtCore.Qt.AlignCenter)
        self.progressBar_2.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_2.setTextDirection(QtWidgets.QProgressBar.BottomToTop)
        self.progressBar_2.setObjectName("progressBar_2")
        self.gridLayout.addWidget(self.progressBar_2, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.wdgProgress, 3, 1, 1, 1)
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem7, 2, 1, 1, 1)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem8, 3, 0, 1, 1)
        spacerItem9 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_2.addItem(spacerItem9, 3, 2, 1, 1)
        self.label_subtitle = QtWidgets.QLabel(self.mainWidget)
        self.label_subtitle.setStyleSheet("    color:#eeeeee;\n"
"    font: 18pt \"Cascadia Code SemiBold\";\n"
"    margin-right:240px;")
        self.label_subtitle.setTextFormat(QtCore.Qt.MarkdownText)
        self.label_subtitle.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_subtitle.setObjectName("label_subtitle")
        self.gridLayout_2.addWidget(self.label_subtitle, 1, 0, 1, 3)
        self.gridLayout_5.addWidget(self.mainWidget, 0, 0, 1, 1)
        self.stkScene.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.gridLayout_9 = QtWidgets.QGridLayout(self.page_3)
        self.gridLayout_9.setObjectName("gridLayout_9")
        self.label_title_3 = QtWidgets.QLabel(self.page_3)
        self.label_title_3.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_3.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_3.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_3.setObjectName("label_title_3")
        self.gridLayout_9.addWidget(self.label_title_3, 0, 0, 1, 4)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem10, 2, 3, 1, 1)
        self.pushButton = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        self.pushButton.setSizePolicy(sizePolicy)
        self.pushButton.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton.setObjectName("pushButton")
        self.gridLayout_9.addWidget(self.pushButton, 2, 2, 1, 1)
        spacerItem11 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_9.addItem(spacerItem11, 2, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.page_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_6.sizePolicy().hasHeightForWidth())
        self.pushButton_6.setSizePolicy(sizePolicy)
        self.pushButton_6.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_6.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_9.addWidget(self.pushButton_6, 2, 1, 1, 1)
        spacerItem12 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem12, 1, 1, 1, 2)
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_9.addItem(spacerItem13, 3, 1, 1, 2)
        self.gridLayout_9.setRowStretch(1, 1)
        self.stkScene.addWidget(self.page_3)
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.gridLayout_10 = QtWidgets.QGridLayout(self.page_4)
        self.gridLayout_10.setObjectName("gridLayout_10")
        self.label_title_4 = QtWidgets.QLabel(self.page_4)
        self.label_title_4.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_4.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_4.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_4.setObjectName("label_title_4")
        self.gridLayout_10.addWidget(self.label_title_4, 0, 0, 1, 4)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem14, 2, 3, 1, 1)
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem15, 3, 1, 1, 2)
        self.pushButton_5 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_5.sizePolicy().hasHeightForWidth())
        self.pushButton_5.setSizePolicy(sizePolicy)
        self.pushButton_5.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_5.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_10.addWidget(self.pushButton_5, 2, 1, 1, 1)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout_10.addItem(spacerItem16, 2, 0, 1, 1)
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_10.addItem(spacerItem17, 1, 1, 1, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.page_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_2.sizePolicy().hasHeightForWidth())
        self.pushButton_2.setSizePolicy(sizePolicy)
        self.pushButton_2.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_2.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_10.addWidget(self.pushButton_2, 2, 2, 1, 1)
        self.gridLayout_10.setRowStretch(1, 1)
        self.stkScene.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_5.setStyleSheet("")
        self.page_5.setObjectName("page_5")
        self.gridLayout_11 = QtWidgets.QGridLayout(self.page_5)
        self.gridLayout_11.setObjectName("gridLayout_11")
        self.pushButton_4 = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_4.sizePolicy().hasHeightForWidth())
        self.pushButton_4.setSizePolicy(sizePolicy)
        self.pushButton_4.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_4.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_11.addWidget(self.pushButton_4, 2, 1, 1, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.page_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_3.sizePolicy().hasHeightForWidth())
        self.pushButton_3.setSizePolicy(sizePolicy)
        self.pushButton_3.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_3.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_11.addWidget(self.pushButton_3, 2, 2, 1, 1)
        self.label_title_5 = QtWidgets.QLabel(self.page_5)
        self.label_title_5.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_5.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_5.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_5.setObjectName("label_title_5")
        self.gridLayout_11.addWidget(self.label_title_5, 0, 0, 1, 4)
        spacerItem18 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.gridLayout_11.addItem(spacerItem18, 3, 1, 1, 2)
        self.wdgIntraCT = QtWidgets.QWidget(self.page_5)
        self.wdgIntraCT.setMinimumSize(QtCore.QSize(600, 450))
        self.wdgIntraCT.setMaximumSize(QtCore.QSize(600, 450))
        self.wdgIntraCT.setStyleSheet("border-image:url(C:/Leon/image/IntraCT.jpg);\n"
"align:right;")
        self.wdgIntraCT.setObjectName("wdgIntraCT")
        self.gridLayout_11.addWidget(self.wdgIntraCT, 1, 1, 1, 2)
        self.stkScene.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_6.setObjectName("page_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_7.setGeometry(QtCore.QRect(369, 680, 324, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_7.sizePolicy().hasHeightForWidth())
        self.pushButton_7.setSizePolicy(sizePolicy)
        self.pushButton_7.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_7.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.label_title_6 = QtWidgets.QLabel(self.page_6)
        self.label_title_6.setGeometry(QtCore.QRect(78, 116, 1236, 100))
        self.label_title_6.setMinimumSize(QtCore.QSize(0, 100))
        self.label_title_6.setMaximumSize(QtCore.QSize(16777215, 100))
        self.label_title_6.setStyleSheet("    color:#eeeeee;\n"
"    font: 64pt \"Cascadia Code SemiBold\";\n"
"    padding:0px;\n"
"    margin:0px;")
        self.label_title_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title_6.setObjectName("label_title_6")
        self.pushButton_8 = QtWidgets.QPushButton(self.page_6)
        self.pushButton_8.setGeometry(QtCore.QRect(700, 680, 324, 150))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Maximum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.pushButton_8.sizePolicy().hasHeightForWidth())
        self.pushButton_8.setSizePolicy(sizePolicy)
        self.pushButton_8.setMinimumSize(QtCore.QSize(324, 150))
        self.pushButton_8.setStyleSheet("QPushButton{\n"
"font: 48pt \"Arial\";\n"
"color:#666666;\n"
"border-radius:24px;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(0, 155, 155, 255), stop:0.2 rgba(88, 239, 255, 255), stop:0.5 rgba(88, 239, 255, 255), stop:0.75 rgba(0, 200, 200, 255),  stop:1 rgba(0, 155, 155, 255));\n"
"padding: 0px 20px;\n"
"margin-bottom:5px;\n"
"margin-right:3px;\n"
"}\n"
"\n"
"QPushButton:hover{\n"
"color:#aa3333;\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:0, y2:1, stop:0 rgba(50, 155, 155, 255), stop:0.2 rgba(150, 239, 255, 255), stop:0.5 rgba(150, 239, 255, 255), stop:0.75 rgba(50, 200, 200, 255),  stop:1 rgba(50, 155, 155, 255));\n"
"}\n"
"\n"
"QPushButton:pressed{\n"
"margin-top:5px;\n"
"margin-bottom:0px;\n"
"margin-left:3px;\n"
"margin-right:0px;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.tableView = QtWidgets.QTableView(self.page_6)
        self.tableView.setGeometry(QtCore.QRect(390, 380, 581, 171))
        self.tableView.setObjectName("tableView")
        self.tableView.horizontalHeader().setSortIndicatorShown(False)
        self.stkScene.addWidget(self.page_6)
        self.gridLayout_3.addWidget(self.stkScene, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1280, 25))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stkScene.setCurrentIndex(5)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "intra-operative"))
        self.label_4.setText(_translate("MainWindow", "Guidance"))
        self.label_title_2.setText(_translate("MainWindow", "AitherBot"))
        self.label_5.setText(_translate("MainWindow", "pre-operative"))
        self.label_6.setText(_translate("MainWindow", "Planning"))
        self.label_subtitle_2.setText(_translate("MainWindow", "Lung Surgical Robotic"))
        self.label_title.setText(_translate("MainWindow", "AitherBot"))
        self.label.setText(_translate("MainWindow", "Robot System"))
        self.label_2.setText(_translate("MainWindow", "Motion Tracker"))
        self.label_subtitle.setText(_translate("MainWindow", "Lung Surgical Robotic"))
        self.label_title_3.setText(_translate("MainWindow", "Setting robot"))
        self.pushButton.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_6.setText(_translate("MainWindow", "Back"))
        self.label_title_4.setText(_translate("MainWindow", "Setting Laser"))
        self.pushButton_5.setText(_translate("MainWindow", "Back"))
        self.pushButton_2.setText(_translate("MainWindow", "Confirm"))
        self.pushButton_4.setText(_translate("MainWindow", "Back"))
        self.pushButton_3.setText(_translate("MainWindow", "Confirm"))
        self.label_title_5.setText(_translate("MainWindow", "Intra-op CT Scan"))
        self.pushButton_7.setText(_translate("MainWindow", "Back"))
        self.label_title_6.setText(_translate("MainWindow", "Import CT"))
        self.pushButton_8.setText(_translate("MainWindow", "Confirm"))
